### ISSUE TITLE
GDPR Delete not working

### ISSUE THREAD

**Issue by chumanfu** [HubSpot/hubspot-api-php#102]
Calling the following is throwing authentication issues:

$client->crm()->contacts()->gdprApi()->postCrmV3ObjectsContactsGdprDelete($objectId);

Looking at the code I can see that the changes in #68 have introduced this issue, which is strange since it is supposed to fix it.
The underlying issue is that the configuration details are empty due to the GDPRApi being created with no params.

I have also tried to follow the example from here:
https://developers.hubspot.com/docs/api/crm/contacts

1. There is a syntax error in the code:
    $apiResponse = $client->crm()->contacts()->gdprDelete()->gdprApi()->post-/crm/v3/objects/contacts/gdprDelete($PublicGdprDeleteInput);
2. There isn't a gdprDelete object.

**Comment by ksvirkou-hubspot** [comment]
Hi @chumanfu 
this API in beta and it isn't work on API side

**Comment by chumanfu** [comment]
@ksvirkou-hubspot 
Thanks for you reply.
It looks like the the API is now in GA

https://developers.hubspot.com/changelog/new-v3-engagement-apis-in-beta-and-contacts-gdpr-delete-endpoint-moves-to-general-availability

When will the SDK be fix?
Is there a way of raising a PR to fix it?

**Comment by ksvirkou-hubspot** [comment]
@chumanfu 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/6.0.0), please?

**Comment by chumanfu** [comment]
This is still not working. As stated previously the construct to GDPRApi is being passed with no parameters in `HubSpot\Discovery\Crm\Contacts\Discovery`.

Can this issue be re-opened until this is fixed please?

When will this be fixed?
