### ISSUE TITLE
Webhook Subscription Duplicate App ID

### ISSUE THREAD

**Issue by gpn273** [HubSpot/hubspot-api-php#112]
On the Subscriptions API Client, I can see that on most endpoints you must provide a `appId` and a `appId2` property. Could you please explain why this is required? What is the purpose of `appId2`? 

I can see the change was introduced as of 5.1.0 but there didn't appear to be a mention about this change within your release notes.

5.0.0 - https://github.com/HubSpot/hubspot-api-php/blob/5.0.0/codegen/Webhooks/Api/SubscriptionsApi.php#L388
5.1.0 - https://github.com/HubSpot/hubspot-api-php/blob/5.1.0/codegen/Webhooks/Api/SubscriptionsApi.php#L398

I can see on all requests, that `appId` is ignored if `appId2` is provided, which will always be replaced since the code type-hint indicates that you must provide both. 

Reference: https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Webhooks/Api/SubscriptionsApi.php#L316

Could this be an error in your specification file, so when the code is auto-generated it's producing this confusing code smell?

**Comment by chumanfu** [comment]
I have also noticed this in the Timeline event template endpoint too. Upgrading from 5 -> 6 broke my integration.

**Comment by ksvirkou-hubspot** [comment]
Hey Everyone 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/7.0.0) ?
