### ISSUE TITLE
vendor/hubspot/api-client/codegen/Webhooks/ObjectSerializer.php

### ISSUE THREAD

**Issue by AydanBeytulov** [HubSpot/hubspot-api-php#113]
Mistake in **toQueryValue** function. 
There isn't $value variable.

**Comment by AydanBeytulov** [comment]
Same for **vendor/hubspot/api-client/codegen/Crm/Properties/ObjectSerializer.php**

**Comment by AydanBeytulov** [comment]
Here: **vendor/hubspot/api-client/codegen/Crm/Contacts/ObjectSerializer.php**

**Comment by ksvirkou-hubspot** [comment]
I'll fix it as soon as possible

**Comment by JshGrn** [comment]
Please let us know when resolved

**Comment by ksvirkou-hubspot** [comment]
Hi Everyone 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/6.0.1)?
