### ISSUE TITLE
Undefined variable $value

### ISSUE THREAD

**Issue by runthis** [HubSpot/hubspot-api-php#114]
**File**: `hubspot/api-client/codegen/Crm/Contacts/ObjectSerializer.php`
**Line**: `174`
**Method**: `toQueryValue`

**Issue**: In the if/elseif/else block it looks for `$value` which doesn't exist.

**Why**: Accessing an undefined variable has been graduated from a notice to an actual error: https://www.php.net/manual/en/migration80.incompatible.php

**Fix?**: Changing it to `$object` resolves the issue.

**Comment by runthis** [comment]
Same issue exists on all of the `ObjectSerializer.php` files.

**Comment by ksvirkou-hubspot** [comment]
Hi @runthis 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/6.0.1)?
