### ISSUE TITLE
These conditions will never be true

### ISSUE THREAD

**Issue by leo108** [HubSpot/hubspot-api-php#117]
Comparing two different strings will never be true.

1. https://github.com/HubSpot/hubspot-api-php/blob/6.0.1/codegen/Crm/Contacts/Api/SearchApi.php#L183
2. https://github.com/HubSpot/hubspot-api-php/blob/6.0.1/codegen/Crm/Contacts/Api/SearchApi.php#L195
3. https://github.com/HubSpot/hubspot-api-php/blob/6.0.1/codegen/Crm/Contacts/Api/SearchApi.php#L208-L209

**Comment by ksvirkou-hubspot** [comment]
hi @leo108 
it is codegen and we can't change it

**Comment by atanasiuk-hubspot** [comment]
This is an automatically generated code, so the conditions will never be true, but it's ok in this cases
