### ISSUE TITLE
Associations request body format

### ISSUE THREAD

**Issue by PeteDMS** [HubSpot/hubspot-api-php#120]
crm()->associations()->batchApi()->read() formats the request body incorrectly. Currently it just sends the ID on its own, when it needs to be in the following JSON format:

{
  "inputs": [
    {
      "id": "1234"
    }
  ]
}

**Comment by ksvirkou-hubspot** [comment]
Sorry but I don’t understand you 
now this method [this model (BatchInputPublicObjectId)](https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Crm/Associations/Model/BatchInputPublicObjectId.php)
and this model convert it to  the same format that you provided
