### ISSUE TITLE
Hubspot/Client/Crm/Objects no way to set values

### ISSUE THREAD

**Issue by fjrsaracho** [HubSpot/hubspot-api-php#124]
According to this forum post: https://community.hubspot.com/t5/APIs-Integrations/Hubspot-API-How-do-you-use-IN-filter-operator/td-p/512907

There is no way to set Values instead Value in Hubspot/Client/Crm/Objects/Filter. It allows to set criteria in but you cannot set array values.

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-api-php/pull/123

**Comment by ksvirkou-hubspot** [comment]
Hi @fjrsaracho 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/8.1.0)?

**Comment by ksvirkou-hubspot** [comment]
CC @huzaifaarain

**Comment by fjrsaracho** [comment]
Confirm that value is on 8.1. 

Thanks you!
