### ISSUE TITLE
retrieve the response headers for crm()->contacts()->searchApi()->doSearch

### ISSUE THREAD

**Issue by buonzz** [HubSpot/hubspot-api-php#125]
Hi,

In https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Crm/Contacts/Api/SearchApi.php#L129
I've noticed that the `$response->getHeaders()` is passed as result of `doSearchWithHttpInfo` function
```
            switch($statusCode) {
                case 200:
                    if ('\HubSpot\Client\Crm\Contacts\Model\CollectionResponseWithTotalSimplePublicObjectForwardPaging' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HubSpot\Client\Crm\Contacts\Model\CollectionResponseWithTotalSimplePublicObjectForwardPaging', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
```

but when it is being returned in https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Crm/Contacts/Api/SearchApi.php#L127-L130
the `list` only returns the `CollectionResponseWithTotalSimplePublicObjectForwardPaging`

What if I wanted to get it return the values returned by `$response->getHeaders()` as well?

Thanks in advance.

**Comment by ksvirkou-hubspot** [comment]
hi @buonzz 
use doSearchWithHttpInfo

```php
$hubSpot->crm()->contacts()->searchApi()->doSearchWithHttpInfo(@request)
```

**Comment by ksvirkou-hubspot** [comment]
hi @buonzz 
use doSearchWithHttpInfo

```php
$hubSpot->crm()->contacts()->searchApi()->doSearchWithHttpInfo(@request)
```
