### ISSUE TITLE
crm()->companies()->getAll() fails with message "Unable to infer object type from: false"

### ISSUE THREAD

**Issue by soxyl** [HubSpot/hubspot-api-php#128]
I started working with the Hubspot API client for PHP and ran into an issue that looks like a bug to me.

I'm trying to get a list of all companies using the `crm()->companies()->getAll()` Method. Doing this I get the following message from the API.

```
  [HubSpot\Client\Crm\Companies\ApiException (400)]                                                                                                                
  [400] Client error: `GET https://api.hubapi.com/crm/v3/objects/companies?limit=100&associations=false&archived=false` resulted in a `400 Bad Request` response:  
  {"status":"error","message":"Unable to infer object type from: false","correlationId":.....................
```

Looking exactly at the error message you can see that the `associactions` parameter is set to false.

I think this happens because `HubSpot\Discovery\Crm\ObjectDiscovery::getAll()` calls the `getPage(...)` method with `$archived` as fifth property. In `HubSpot\Client\Crm\Companies\Api\BasicApi::getPage(...)` it is the sixth property though.

The fifth property in the `BasicApi` class is `$associations`. This is why in the API call sets this parameter to `false`.

**Comment by fieryprophet** [comment]
Looks like it was introduced in this commit: https://github.com/HubSpot/hubspot-api-php/commit/3741b38795d75b0aa17b4cfb339c7e95f60e0e0a, so downgrading to v5.0.0 fixes it for now.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
I ve fixed it [in the latest version ](https://github.com/HubSpot/hubspot-api-php/releases/tag/8.1.1)

**Comment by jonjieviduya** [comment]
I'm currently getting the same error. Any other ideas?
