### ISSUE TITLE
Is this library using semantic versioning?

### ISSUE THREAD

**Issue by alexanderschnitzler** [HubSpot/hubspot-api-php#13]
Hi folks, I just updated the library from 1.3.1 to 1.3.2 and the public api broke:

1.3.1: https://github.com/HubSpot/hubspot-api-php/blob/1.3.1/codegen/Crm/Contacts/Api/BatchApi.php#L670
1.3.2: https://github.com/HubSpot/hubspot-api-php/blob/1.3.2/codegen/Crm/Contacts/Api/BatchApi.php#L682

The method signature has changed from

```php
    public function read($archived = false, $batch_read_input_simple_public_object_id = null)
    {
        list($response) = $this->readWithHttpInfo($archived, $batch_read_input_simple_public_object_id);
        return $response;
    }
```
to
```php
    public function read($batch_read_input_simple_public_object_id, $archived = false)
    {
        list($response) = $this->readWithHttpInfo($batch_read_input_simple_public_object_id, $archived);
        return $response;
    }
```

I only realized that since phpstan threw new errors. If your library is following semantic versioning, this change is a no go. Please clarify which version strategy you are using.

Thanks

**Comment by ksvirkou-hubspot** [comment]
Hi 
We have already fixed it 
it was our fail but 
We are following semantic versioning
thank you

**Comment by atanasiuk-hubspot** [comment]
Hi, @alexanderschnitzler, you should upgrade to v1.3.3 which fixes that breaking change

**Comment by atanasiuk-hubspot** [comment]
Looks to be resolved, feel free to reopen if any questions
