### ISSUE TITLE
Can not create Ticket

### ISSUE THREAD

**Issue by BatunaAz** [HubSpot/hubspot-api-php#139]
Hello guys, 

I have successfully created ticket by node API use following array: 

$properties = [
    "subject" => "troubleshoot report",
    "hs_pipeline" => "support_pipeline",
    "hs_pipeline_stage" => "open",
    "hs_ticket_priority" => "HIGH",
    "hubspot_owner_id" => "910901",
    
];

But [hubspot-api-php](https://github.com/HubSpot/hubspot-api-php) can not create ticket by 
$properties = [
    "subject" => "troubleshoot report",
    "hs_pipeline" => "support_pipeline",
    "hs_pipeline_stage" => "open",
    "hs_ticket_priority" => "HIGH",
    "hubspot_owner_id" => "910901",
    
];
this array. It returned {"status":"error","message":"Cannot create object with type: TICKET. The following required properties were missing}

NODE can create. WHY php can not?

**Comment by ksvirkou-hubspot** [comment]
Hey @BatunaAz 
I ve tried it on js and it doesn’t work
```javascript
const properties = {
        "subject": "troubleshoot report",
        "hs_pipeline": "support_pipeline",
        "hs_pipeline_stage": "open",
        "hs_ticket_priority": "HIGH",
        "hubspot_owner_id": "*",
    };
    const SimplePublicObjectInput = { properties };

    const response = await hubspotClient.crm.tickets.basicApi.create(SimplePublicObjectInput).catch((err) => {
        console.error(err)
    });
    console.log(response)
```
it returns 
```JSON
{
    code: 400,
    body: {
        status: 'error',
        message: 'Property values were not valid: [{"isValid":false,"message":"open is not a valid pipeline stage ID. Valid options are: pipelineId=0 : [1, 2, 3, 4]","error":"INVALID_OPTION","name":"hs_pipeline_stage"}]',
        correlationId: 'd2e253f9-c603-4d0d-aceb-28f39159ae0d',
        category: 'VALIDATION_ERROR'
    }
}
```
