### ISSUE TITLE
team membership is always NULL on owner API

### ISSUE THREAD

**Issue by mshamaseen** [HubSpot/hubspot-api-php#150]
the issue:
I was expecting to receive [primary](https://developers.hubspot.com/docs/api/crm/owners) property on the `teams` object of the **owner API**, but `membership` was there instead, and it is always NULL.

how to produce:
`Factory::createWithApiKey($key)->crm()->owners()->getAll();`

**Comment by ksvirkou-hubspot** [comment]
@mshamaseen 
I ve just checked it and it works correctly on version 8.3
