### ISSUE TITLE
More README examples please (deal creation / association)

### ISSUE THREAD

**Issue by stuartcusackie** [HubSpot/hubspot-api-php#155]
Can we get a README example of deal creation and association with a contact?

**Comment by ksvirkou-hubspot** [comment]
Hi @stuartcusackie 
You an get it in [the docs](https://developers.hubspot.com/docs/api/crm/deals)

**Comment by stuartcusackie** [comment]
Thank you. Yes, I figured this out using Guzzle directly with a PUT request. I was looking for a way to use this package to create the association instead.

The deal is that same as the contact creation:

```
$dealInput = new \HubSpot\Client\Crm\Deals\Model\SimplePublicObjectInput();

$dealInput->setProperties($yourPropertiesArray);

return $hubSpot->crm()->deals()->basicApi()->create($dealInput);
```

But I couldn't figure out the association creation.

**Comment by ksvirkou-hubspot** [comment]
> Thank you. Yes, I figured this out using Guzzle directly with a PUT request but originally I was looking for a way to use this package to create the association instead.
> 
> The deal creation is that same as the contact creation:
> 
> ```
> $dealInput = new \HubSpot\Client\Crm\Deals\Model\SimplePublicObjectInput();
> 
> $dealInput->setProperties($yourPropertiesArray);
> 
> return $hubSpot->crm()->deals()->basicApi()->create($dealInput);
> ```
> 
> But I couldn't figure out the association creation.
if you need batch creation 
https://developers.hubspot.com/docs/api/crm/associations/v3
or 
https://developers.hubspot.com/docs/api/crm/deals
```php
$apiResponse = $client->crm()->deals()->associationsApi()->create("dealId", "toObjectType", "toObjectId", "associationType");
```

**Comment by alucic** [comment]
@ksvirkou-hubspot Would you mind providing a v4 example? Thanks
