### ISSUE TITLE
Schema creation endpoint does not send access token authorization header

### ISSUE THREAD

**Issue by LordFont** [HubSpot/hubspot-api-php#156]
Hello,

while migrating our HubSpot integration from the soon to be deprecated API keys to the new recommended private apps access tokens I ran into some issues when trying to run custom objects schema creation. It simply refused to authenticate. I contacted HubSpot support and we had a bit of back and of forth until I finally realised that this is because the current version of the PHP library, when using schemas API, does not check for existence of access tokens and does not accordingly set the authorisation header.

This can be quickly fixed by adding the required if check which is present in the rest of the library.

Additionally, I noticed the same check is missing from the CRM import portion of the codebase.

**Comment by echantigny** [comment]
Ran into this same issue just now and came to report it.

**Comment by GlennBags** [comment]
Any advancement on this? We're looking to migrate as well.

**Comment by gpn273** [comment]
Similar situation here too. Using version 8.4.1

**Comment by chumanfu** [comment]
I too am having this issue. Needs sorting by the end of the month please :-)

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I've fixed it 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/9.0.0)?
