### ISSUE TITLE
Example to connect a visitor/contact to a chat is not working

### ISSUE THREAD

**Issue by echantigny** [HubSpot/hubspot-api-php#158]
Hi,

I'm trying to get a token to assign a contact to a chat window in my website and the example in the documentation is not working.   I know that my key and the contact are all working because I can query the endpoint manually and it works.  I also tried to use the same hubspot factory to query for that same contact and I get the result just fine.

The code I'm using always gives this error:
`Unable to discover "tokens" client`

```
use HubSpot\Client\Conversations\VisitorIdentification\Model\IdentificationTokenGenerationRequest;
use HubSpot\Factory;

$hubspot = Factory::createWithAccessToken("my app token");

$IdentificationTokenGenerationRequest = new IdentificationTokenGenerationRequest(['email' => "myemail@address.com", 'first_name' => "First", 'last_name' => "Last"]);
try {
    $apiResponse = $hubspot->conversations()->visitorIdentification()->tokens()->create()->generateApi()->generateToken($IdentificationTokenGenerationRequest);
} catch (\Exception $e) {
    echo "Exception when calling generate_api->generate_token: ", $e->getMessage();
}
```

The documentation also has other errors:
_HubSpot\Client\Conversations\VisitorIdentification\Tokens\Create\ApiException_ actually doesn't exist
`use HubSpot\Client\Conversations\VisitorIdentification\Model\IdentificationTokenGenerationRequest;` is missing at the top

**Comment by ksvirkou-hubspot** [comment]
@echantigny 
Thank you for the issue 
We wil fix it 
Correct example
```php
use HubSpot\Client\Conversations\VisitorIdentification\Model\IdentificationTokenGenerationRequest;
use HubSpot\Factory;

$hubspot = Factory::createWithAccessToken("my app token");

$request = new IdentificationTokenGenerationRequest(['email' => "myemail@address.com", 'first_name' => "First", 'last_name' => "Last"]);
try {
    $apiResponse = $hubspot->conversations()->visitorIdentification()->generateApi()->generateToken($request);
} catch (\Exception $e) {
    echo "Exception when calling generate_api->generate_token: ", $e->getMessage();
}
```
