### ISSUE TITLE
Can't find a way to pass "values" not "value" for "IN" filter operator 

### ISSUE THREAD

**Issue by tigitz** [HubSpot/hubspot-api-php#16]
Hello,

I would like to match this request using the sdk
![image](https://user-images.githubusercontent.com/1524501/91833808-77810a00-ec47-11ea-993d-d6f02e9049bf.png)

Unfortunately it seems there's only a `setValue` method not `setValues`

![image](https://user-images.githubusercontent.com/1524501/91834107-e2cadc00-ec47-11ea-9a87-92ba35d7f74b.png)

**Comment by atanasiuk-hubspot** [comment]
Hi, @tigitz. Does Rest API accept multiply values within one Filter?

As a workaround, multiply values can set within different FilterGroups and "OR" operator: 
https://developers.hubspot.com/docs/api/crm/search

**Comment by atanasiuk-hubspot** [comment]
"IN" operator is not currently supported. A list of supported operators: https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Crm/Contacts/Model/Filter.php#L189

**Comment by tigitz** [comment]
@atanasiuk-hubspot Got it, it's a request I've inspected from my network tab while using the hubspot interface so I assume they internally use the IN operator but haven't documented it yet for public use.

I'll try to work around this limitation with the `OR` filter.

Thanks
