### ISSUE TITLE
Files getSignedUrl only returns url

### ISSUE THREAD

**Issue by andrews05** [HubSpot/hubspot-api-php#161]
The signed url endpoint is supposed to return additional information about the file, including type, name, and dimensions, but these other fields are all null in the response object - only the url has a value.

I think this is possibly an issue with HubSpot itself. I can see the additional fields if I manually make a call to the legacy `/filemanager/api/v3/files`, but `/files/v3/files` isn't working correctly.

**Comment by ksvirkou-hubspot** [comment]
Hi @andrews05 .
It was fixed a few days ago.
I've just checked it and it works correctly.
