### ISSUE TITLE
Upgrade Guzzle package to support ^7.0

### ISSUE THREAD

**Issue by oytuntez** [HubSpot/hubspot-api-php#17]
Guzzle recently released v7, let's add support for it. This is the only package in our (quite big) application lacking support for Guzzle v7.

https://packagist.org/packages/guzzlehttp/guzzle

**Comment by oytuntez** [comment]
Just checked with the upgrade guide of Guzzle, this package looks fine. Will fork and PR.

**Comment by atanasiuk-hubspot** [comment]
Hi, @oytuntez. Upgrading Guzzle package is a bit tricky thing.

The SDK uses [OpenApi Generator](https://github.com/OpenAPITools/openapi-generator) under the hood, so Guzzle dependency must be in sync with Generator dependencies.

How this could be done:
- Send PR to https://github.com/OpenAPITools/openapi-generator for Guzzle 7 support
- Upgrade Guzzle dependency here

**Comment by drjdr** [comment]
@oytuntez @atanasiuk-hubspot @CiiDyR @damiencriado @atymic (#25 #19 #18 #15) 
Can you please verify #19 is working and upvote [This OpenApi PR](https://github.com/OpenAPITools/openapi-generator/pull/7950) ?

**Comment by CiiDyR** [comment]
@drjdr Maybe a matching composer.lock and package version bump would be a good addition?

But otherwise I can confirm that all tests run fine with Guzzle ^7.0 :+1:

**Comment by ksvirkou-hubspot** [comment]
check this version please
 https://github.com/HubSpot/hubspot-api-php/releases/tag/2.3.0
