### ISSUE TITLE
Decouple guzzle and use instead PSR18

### ISSUE THREAD

**Issue by Kleinast** [HubSpot/hubspot-api-php#172]
We use less and less guzzle in our application and replace it with symfony http client.
I feel shame that the hubspot is hard coupled with GuzzleHttp\ClientInterface, it will be great to be able to use any PSR18 implementation or at least HttpPlug 2.x

**Comment by atanasiuk-hubspot** [comment]
There is nothing we can share at the moment, but generally method name can be extracted from operationId:
`get-/crm/v3/objects/contacts_getPage` => `getPage`. Some kind of operationId transformation is needed here.

**Comment by ksvirkou-hubspot** [comment]
We can't do it 
because we generate the SDK by swagger file via [Open API Generator](https://openapi-generator.tech/)
Open API Generator support only guzzle 
If Open API Generator change code it will be possible
