### ISSUE TITLE
RequestTest.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by mvalee** [HubSpot/hubspot-api-php#176]
Namespace of file `/tests/Unit/Http/RequestTest.php` does not correspond with file path, leading to a composer depreciation message:

(note: should be the `Utils` that is incorrect in the file, not the `Unit`, is wrongly highlighted in image below)
![image](https://user-images.githubusercontent.com/12297559/196098610-b71fa828-e02d-4738-a433-f31a95266139.png)

![image](https://user-images.githubusercontent.com/12297559/196098720-ddf2d413-cce0-40b2-921c-b9c18c198062.png)

**Comment by ksvirkou-hubspot** [comment]
Hi @mvalee 
I ve just fixed it
Thank you
