### ISSUE TITLE
9.0.0 breaks assosciation API

### ISSUE THREAD

**Issue by alexgran** [HubSpot/hubspot-api-php#184]
You seem to have regenerated code against v4 of the association api, but that doesn't work.
Hubspot expects a http body, but vendor/hubspot/api-client/codegen/Crm/Tickets/Api/AssociationsApi->createRequest doesn't set one.

**Comment by ksvirkou-hubspot** [comment]
@manojmohangit @alexgran 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/9.0.1), please?
