### ISSUE TITLE
Typo in “CollectionResponsePublicAssociationDefiniton”?

### ISSUE THREAD

**Issue by alexislefebvre** [HubSpot/hubspot-api-php#193]
Should `CollectionResponsePublicAssociationDefiniton` be replaced by `CollectionResponsePublicAssociationDefinition`?

`i` i missing in `Definiton`.

**Comment by ksvirkou-hubspot** [comment]
Hi @alexislefebvre .
Thank you for reporting the issue.
I've fixed it in [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/9.2.2).
