### ISSUE TITLE
Unusable on PHP 8.2

### ISSUE THREAD

**Issue by twisted1919** [HubSpot/hubspot-api-php#202]
> During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectWithAssociations::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/web/vendor/hubspot/api-client/codegen/Crm/Contacts/Model/SimplePublicObjectWithAssociations.php:460
Stack trace:

**Comment by ksvirkou-hubspot** [comment]
Hi, @twisted1919 .
What version of SDK do you use?
I've just checked version 9.2.1 on php 8 and It works correctly.

**Comment by twisted1919** [comment]
@ksvirkou-hubspot - I am sorry, I got a cached version of our vendors in the container we were using and that tricked me. Thank you for looking into this, it was just a misunderstanding.
