### ISSUE TITLE
Lots of depreciated warnings for PHP 8.1

### ISSUE THREAD

**Issue by adam-clarey** [HubSpot/hubspot-api-php#203]
EG:
Deprecated function: Return type of HubSpot\Client\Crm\Deals\Model\SimplePublicObject::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 43 of /app/vendor/hubspot/api-client/codegen/Crm/Deals/Model/SimplePublicObject.php)

Deprecated function: Return type of HubSpot\Client\Crm\Deals\Model\SimplePublicObject::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 43 of /app/vendor/hubspot/api-client/codegen/Crm/Deals/Model/SimplePublicObject.php)

plus more

**Comment by ksvirkou-hubspot** [comment]
Hi, @adam-clarey .
What version of SDK do you use?
I've just checked version 9.2.1 on php 8.1 and It works correctly.

**Comment by ksvirkou-hubspot** [comment]
This problem was solved in version 6.0.0
If you update SDK to 6.0.0 or higher it will work correctly.
