### ISSUE TITLE
Timestamp on Note is January 1970 at Contact object

### ISSUE THREAD

**Issue by jasperpoppe** [HubSpot/hubspot-api-php#207]
I'm using a private app in HubSpot to create contacts and notes.
With the following code I create a HubSpot object:
```php
$hubspot = Factory::createWithAccessToken('the-access-token');
```

The following code is used to create a new note:
```php
$now = new \DateTime('now', new \DateTimeZone('UTC'));
$noteInput = new \HubSpot\Client\Crm\Objects\Model\SimplePublicObjectInput();
$noteInput->setProperties([
    'hs_timestamp' => $now->getTimestamp(),
    'hs_note_body' => 'Hi there!',
]);

$note = $hubspot->crm()->objects()->basicApi()->create('notes', $noteInput);
```

When I check `$note`, I can see that the `created_at` field has the current timestamp.

Now I add the note to an existing contact:
```php
$hubspot->crm()->objects()->associationsApi()->create(
    'contacts',
    $contactId,
    'notes',
    $note['id'],
    'contact_to_note'
);
```

When I check the contact in HubSpot, the timestamp of the note is "January 1970".
<img width="487" alt="Scherm­afbeelding 2023-01-17 om 17 20 34" src="https://user-images.githubusercontent.com/4797859/212954210-a695db85-7d12-4b9c-a47a-c145dde7c08d.png">

Did I forget something in the calls?

**Comment by ksvirkou-hubspot** [comment]
Hi @jasperpoppe .
For `hs_timestamp` you can use either a Unix timestamp in milliseconds or UTC format. 
Workable example:
```php
$now = new \DateTime('now', new \DateTimeZone('UTC'));
$noteInput = new SimplePublicObjectInput();
$noteInput->setProperties([
    'hs_timestamp' => (int)$now->format('Uv'),
    'hs_note_body' => 'Hi there!',
]);

$note = $hubspot->crm()->objects()->basicApi()->create('notes', $noteInput);

$hubspot->crm()->objects()->notes()->associationsApi()->create(
    $note->getId(),
    'contacts',
    '307753',
    [
        new AssociationSpec([
            'association_category' => 'HUBSPOT_DEFINED',
            'association_type_id' => 202,
        ])
    ]
);
```
Sdk version [9.2.2](https://github.com/HubSpot/hubspot-api-php/tree/9.2.2)

**Comment by jasperpoppe** [comment]
Thanks @ksvirkou-hubspot!
`(int)$now->format('Uv')` instead of `$now->getTimestamp()` did the trick for `hs_timestamp`.
