### ISSUE TITLE
9.2.2 requiring php 8.1

### ISSUE THREAD

**Issue by craigivemy** [HubSpot/hubspot-api-php#212]
After installing 9.2.2 via composer, I receive the following error:

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.27`

Tracing this via composer.lock, it seems guzzlehttp 7.5.0 has symfony/deprecation-contracts as a dependency, and the installed version requires PHP 8.1

This may be a rookie error on my part (been a long while since I used PHP and Composer) - but since 9.2.2 docs state PHP requirement of >=7.3, installing 9.2.2 via composer should not contain dependencies that require a php version above this?

**Comment by ksvirkou-hubspot** [comment]
Hi @craigivemy .
I've just it on php `8.0.27` and it works correctly without any error.
Regarding `"symfony/deprecation-contracts": "^2.2 || ^3.0" ` [it requires php `php: >=7.1`](https://packagist.org/packages/symfony/deprecation-contracts#v2.2.0) .
