### ISSUE TITLE
The dependency "symfony/deprecation-contracts" requires PHP >=8.1

### ISSUE THREAD

**Issue by gavin310** [HubSpot/hubspot-api-php#213]
In the readme it says the current package requirements are PHP >= 7.3 but it won't run on anything below PHP 8.1.

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.25. in...`

**Comment by ksvirkou-hubspot** [comment]
Hi @gavin310  .
I've just it on php 8.0.27 and it works correctly without any error.
Regarding "symfony/deprecation-contracts": "^2.2 || ^3.0"  [it requires php php: >=7.1](https://packagist.org/packages/symfony/deprecation-contracts#v2.2.0) .

**Comment by gavin310** [comment]
@ksvirkou-hubspot Thanks for the quick response. You're using v2.2.0 of "symfony/deprecation-contracts" which is indeed compatible with PHP 8.0.x, but when I do "composer require hubspot/api-client" it installs v3.2.0 [which requires >=8.1](https://packagist.org/packages/symfony/deprecation-contracts).

**Comment by gavin310** [comment]
@ksvirkou-hubspot My bad. My local environment was newer than the server so it was installing a later version of the dependencies. Using `composer config platform.php 8.0.25` and then `composer update` fixed it. Sorry for the confusion and thanks again for the quick response.
