### ISSUE TITLE
Example of accessing recently modified objects?

### ISSUE THREAD

**Issue by jamesgraham** [HubSpot/hubspot-api-php#22]
Cannot see how to do this with the new APIs.

https://developers.hubspot.com/docs/api/crm/companies shows List but this does not seem to have a default order or way to sort by modified date?

**Comment by atanasiuk-hubspot** [comment]
Hi, @jamesgraham. Please check POST `/crm/v3/objects/companies/search` [endpoint](https://developers.hubspot.com/docs/api/crm/companies). `sorts` parameter is probably what you need.
