### ISSUE TITLE
Deal filter between highValue

### ISSUE THREAD

**Issue by dansleboby** [HubSpot/hubspot-api-php#220]
Hi,
I only see a setValue and no setHighValue when we try to make a BETWEEN filter on a Deal

How I can do this?

Thanks

**Comment by MichaelNZ85** [comment]
I am having this same issue - there is no way to set the `highValue` filter prop using the API client. Passing the high value in the `values` array does not work.

**Comment by ksvirkou-hubspot** [comment]
I am working on it.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've added `highValue` in [the latest version](https://packagist.org/packages/hubspot/api-client#10.0.0-beta).
