### ISSUE TITLE
2 API calls requires for creating a deal and associating it with a contact

### ISSUE THREAD

**Issue by BurningDog** [HubSpot/hubspot-api-php#234]
I'd like to make a _single_ API call to create a Deal *AND* include an association _at the same time_. According to the documentation this is possible. https://developers.hubspot.com/docs/api/crm/deals#create-deals reads:

> You can also add an associations object to associate your new deal with existing records (e.g., contacts, companies), or activities (e.g., meetings, notes).

https://developers.hubspot.com/docs/api/crm/deals#associations shows the following JSON object which can be sent to the `create deal` API endpoint:

```json
///Example request body
{
  "properties": {
    "amount": "1500.00",
    "closedate": "2019-12-07T16:50:06.678Z",
    "dealname": "New deal",
    "pipeline": "default",
    "dealstage": "contractsent",
    "hubspot_owner_id": "910901"
  },
"associations": [
    {
     "to": {
        "id": 201
      },
      "types": [
        {
          "associationCategory": "HUBSPOT_DEFINED",
          "associationTypeId": 5
        } ]
    }, 
    {
     "to": {
        "id": 301
      },
      "types": [
        {
          "associationCategory": "HUBSPOT_DEFINED",
          "associationTypeId": 3
        } ]
}]
}
```

However, the `hubspot-api-php` library requires 2 API calls to do the same thing.

1. Create the Hubspot Deal
2. Associate the Deal with the desired association.

This is because the `create()` function in `\HubSpot\Client\Crm\Deals\Api\BasicApi` only takes a single argument of type `\HubSpot\Client\Crm\Deals\Model\SimplePublicObjectInput` and `SimplePublicObjectInput` only allows a `properties` property and not an `associations` property.

The `create()` function in `\HubSpot\Client\Crm\Deals\Api\AssociationsApi` expects that a Deal has first been created, as its first argument is an existing deal id:

```php
    /**
     * Operation create
     *
     * Create
     *
     * @param  int $deal_id deal_id (required)
     * @param  string $to_object_type to_object_type (required)
     * @param  int $to_object_id to_object_id (required)
     * @param  \HubSpot\Client\Crm\Deals\Model\AssociationSpec[] $association_spec association_spec (required)
     *
     * @throws \HubSpot\Client\Crm\Deals\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Deals\Model\LabelsBetweenObjectPair|\HubSpot\Client\Crm\Deals\Model\Error
     */
    public function create($deal_id, $to_object_type, $to_object_id, $association_spec)
```

Therefore there is no way, using the `hubspot-api-php` library, that a single API call can be done to create a deal and associate it with, say, a contact - which means the library does not implement the official Hubspot docs as at https://developers.hubspot.com/docs/api/crm/deals#associations

I would expect to be able to use the `create()` function in the `BasicApi` class to pass optional associations to.

This issue was originally reported at https://github.com/HubSpot/hubspot-api-php/issues/155 but the answer there doesn't answer the question, unfortunately.

**Comment by ksvirkou-hubspot** [comment]
Hi @BurningDog .
You can create a deal and associations in a single API call in [the latest version of the SDK (10.0.0-beta)](https://packagist.org/packages/hubspot/api-client#10.0.0-beta).

**Comment by BurningDog** [comment]
Thanks @ksvirkou-hubspot.

I'm not sure why it's so difficult to create an association using this PHP library. In JSON, the API is simple - add the following to the JSON:

```json
{
  "associations": [
    {
      "to": {
        "id": "58301"
      },
      "types": [
        {
          "associationCategory": "HUBSPOT_DEFINED",
          "associationTypeId": 3
        }
      ]
    }
  ]
}
```

But to do the same using the library, it is:

```php
$association_spec = [
    new \HubSpot\Client\Crm\Deals\Model\AssociationSpec([
        'association_category' => \HubSpot\Client\Crm\Deals\Model\AssociationSpec::ASSOCIATION_CATEGORY_HUBSPOT_DEFINED,
        'association_type_id' => 3, // The number 3 is the association of a Deal with a Contact
    ]),
];
$associations = [
    new \HubSpot\Client\Crm\Deals\Model\PublicAssociationsForObject([
        'to' => [
            'id' => $properties['hubspot_contact_vid'],
        ],
        'types' => $association_spec,
    ])
];
unset($properties['hubspot_contact_vid']); // This field doesn't exist in Hubspot
$data['associations'] = $associations;

$data['properties'] = $properties;

$simple_public_object_input = new \HubSpot\Client\Crm\Deals\Model\SimplePublicObjectInputForCreate($data);

$apiResponse = $this->client->crm()->deals()->basicApi()->create($simple_public_object_input);
```

This required reading the code of `AssociationSpec`, `PublicAssociationsForObject` and `SimplePublicObjectInputForCreate` to figure out how it expects objects/arrays internally, which is the sign of lacking documentation and unnecessarily complicated code, and much lost time on my part.
