### ISSUE TITLE
Associations API v3 removed from objects, but v4 not included

### ISSUE THREAD

**Issue by MichaelNZ85** [HubSpot/hubspot-api-php#235]
The associations API v3 has been removed from objects like deals and companies in the latest release (10.0.0-beta), as per the changelog. However, there is no associations API v4 included, meaning that there is currently no way to manage associations through the client and raw HTTP requests must be used instead.

**Comment by ksvirkou-hubspot** [comment]
Hi @MichaelNZ85 .
We generate the SDK by Hubspot swagger files.
Hubspot have removed these methods from the swagger files.

**Comment by MichaelNZ85** [comment]
So why hasn't the v4 associations API been addedd into the SDK? [It's in the API docs](https://developers.hubspot.com/docs/api/crm/associations) (which is what I assume you mean by 'Hubspot swagger files').

**Comment by ksvirkou-hubspot** [comment]
I don't know why samples don't work.
```php
$hubspot->crm()->associations()->v4();
$hubspot->crm()->objects()->associationsApi();
```
