### ISSUE TITLE
No properties found to update, please provide at least one.

### ISSUE THREAD

**Issue by jonjieviduya** [HubSpot/hubspot-api-php#242]
I'm trying to use the code for the contact update but it is returning an error.

**Error**
> No properties found to update, please provide at least one.

**Here's my code**
```
$contactId = $searchResult['results'][0]['id'];
$properties = [
    'properties' => [
        'firstname' => $request['first_name'],
        'lastname' => $request['last_name'],
        'jobtitle' => $request['job_title'],
        'email' => $request['email'],
        'phone' => $request['phone']
    ]
];

$simplePublicObjectInput = new SimplePublicObjectInput($properties);

$client->crm()->contacts()->basicApi()->update($contactId, $simplePublicObjectInput);
```

**Comment by ksvirkou-hubspot** [comment]
Hi @jonjieviduya .
What version of the SDK do you use?

**Comment by jonjieviduya** [comment]
> Hi @jonjieviduya .
> 
> What version of the SDK do you use?

@ksvirkou-hubspot it's the version 3

**Comment by ksvirkou-hubspot** [comment]
Workable example:
```php
use HubSpot\Factory;
use HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput;

$hubspot = Factory::createWithAccessToken('pat-na1-4497734a-28b9-441b-8775-5e173fe447f1');

$contactInput = new SimplePublicObjectInput([
    'properties' => [
        'firstname' => 'Mike',
        'lastname' => 'Green',
        'jobtitle' => 'Software engineer',
        'email' => 'Green@example.com',
        'phone' => '+123456789012'
    ],
]);

$response = $hubspot->crm()->contacts()->basicApi()->create($contactInput);
```
The SDK version is 3.1.0 .

**Comment by jonjieviduya** [comment]
> Workable example:
> 
> ```php
> 
> use HubSpot\Factory;
> 
> use HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput;
> 
> 
> 
> $hubspot = Factory::createWithAccessToken('*');
> 
> 
> 
> $contactInput = new SimplePublicObjectInput([
> 
>     'properties' => [
> 
>         'firstname' => 'Mike',
> 
>         'lastname' => 'Green',
> 
>         'jobtitle' => 'Software engineer',
> 
>         'email' => 'Green@example.com',
> 
>         'phone' => '+123456789012'
> 
>     ],
> 
> ]);
> 
> 
> 
> $response = $hubspot->crm()->contacts()->basicApi()->create($contactInput);
> 
> ```
> 
> The SDK version is 3.1.0 .

You are not using the update method. You're using the create

**Comment by jonjieviduya** [comment]
So, what's wrong or missing in my code?

**Comment by ksvirkou-hubspot** [comment]
I've just checked your code and it works correctly.
```php
$request = [
    'first_name' => 'Mike1',
    'last_name' => 'Green1',
    'job_title' => 'Software engineer1',
    'email' => 'Green1@example.com',
    'phone' => '+123456789011'
];
$contactId = '323751';
$properties = [
    'properties' => [
        'firstname' => $request['first_name'],
        'lastname' => $request['last_name'],
        'jobtitle' => $request['job_title'],
        'email' => $request['email'],
        'phone' => $request['phone']
    ]
];

$simplePublicObjectInput = new SimplePublicObjectInput($properties);

$client->crm()->contacts()->basicApi()->update($contactId, $simplePublicObjectInput);
```

**Comment by jonjieviduya** [comment]
uhm, that's strange

**Comment by ksvirkou-hubspot** [comment]
I recommend you to check $request variable and $simplePublicObjectInput before sending.
Also if you use private app access token you can check your request on private app logs(Settings -> Integrations -> Private Apps -> your private app -> Logs).

**Comment by ksvirkou-hubspot** [comment]
Feel free to reopen if any questions.
