### ISSUE TITLE
searchApi: Operator BETWEEN requires a highValue

### ISSUE THREAD

**Issue by seven21** [HubSpot/hubspot-api-php#245]
**Expected behaviour**
I try to use the search api with an "between" operator. Have copied the code from the hubspot documentation page. Calling the search api should return a list of deals

**Actual behaviour**
Response is always "Exception when calling search_api->do_search: [400] Client error: `POST https://api.hubapi.com/crm/v3/objects/deals/search` resulted in a `400 Bad Request` response: {"status":"error","message":"Invalid input JSON on line 1, column 185: operator BETWEEN requires a highValue","correlati (truncated...)

**Possible issue**
I checked the file codegen/Crm/Deals/Model/Filter.php. Seems to be that the high_value parameter is not handled

**Code example**
`
$client = Factory::createWithAccessToken(config('hubspot.key'));

        $filter1 = new Filter([
            'value' => 'decisionmakerboughtin',
            'property_name' => 'dealstage',
            'operator' => 'EQ'
        ]);

        $filter2 = new Filter([
            'value' => '2023-02-01',
            'high_value' => '2023-05-01',
            'property_name' => 'date_signed',
            'operator' => 'BETWEEN'
        ]);

        $filterGroup1 = new FilterGroup([
            'filters' => [$filter1, $filter2]
        ]);

        $publicObjectSearchRequest = new PublicObjectSearchRequest([
            'filter_groups' => [$filterGroup1],
            'sorts' => ['date_signed'],
            'properties' => ["dealname,amount,recurring_revenue_amount,dealstage,date_signed"],
            'limit' => 100,
            'after' => 0,
        ]);

        try {
            $apiResponse = $client->crm()->deals()->searchApi()->doSearch($publicObjectSearchRequest);
            var_dump($apiResponse);
        } catch (ApiException $e) {
            echo "Exception when calling search_api->do_search: ", $e->getMessage();
        }
`

**EDIT**
Just recognized that this issue was already reported and should be resolved in 10.0.0 beta version. [https://github.com/HubSpot/hubspot-api-php/issues/220](https://github.com/HubSpot/hubspot-api-php/issues/220)

The "Filter.php" does now handle the high_value but I still get the an error. 

**Error is now:**
 `400 Bad Request` response: {"status":"error","message":"There was a problem with the request.","correlationId":"ac637434-0ba7-4369-b558-0531b6489f0 (truncated...)

When I remove the BETWEEN operator and try other options it always works

**Comment by MichaelNZ85** [comment]
This is fixed in the 10.0.0 beta version, as you said, but that version also removes the v3 associations API, so you can no longer call `crm()->deals()->associationsApi()->create()`, etc. Just letting you know.
