### ISSUE TITLE
Something I don't understand

### ISSUE THREAD

**Issue by pdeberranger** [HubSpot/hubspot-api-php#260]
Hi team,
I've find this in codegen/Crm/Contacts/Api/BasicApi.php:429 :

if (**'\HubSpot\Client\Crm\Contacts\Model\SimplePublicObject' === '\SplFileObject'**) {
    $content = $response->getBody(); //stream goes to serializer
} else {
    $content = (string) $response->getBody();
    if (**'\HubSpot\Client\Crm\Contacts\Model\SimplePublicObject' !== 'string'**) {
        $content = json_decode($content);
    }
}

I don't know if the if () are ok, for me not because it's always false and true!

**Comment by ksvirkou-hubspot** [comment]
Hi @pdeberranger .
The SDK is auto-generated based on swagger files and these if-constructions are caused by using of OpenApiGenerator.
They works good.
