### ISSUE TITLE
How to add filters in the blog endpoint

### ISSUE THREAD

**Issue by psjavi** [HubSpot/hubspot-api-php#266]
Hi,

I'm doing a request using the following code:

`$this->client->cms()->blogs()->blogPosts()->blogPostsApi()->getPage(...)`

How can I add params to the request in order to do some filtering? For example, I need to do the following request:

https://api.hubapi.com/cms/v3/blogs/posts?contentGroupId=XXXX&state=PUBLISHED

**Comment by avblink** [comment]
```
    $settings = [
      'content_group_id' => [YOUR BLOG ID],
      'offset' => 1,
      'limit' => 2,
      'state' => 'PUBLISHED',
      'sort' => '-publish_date',
      'property'  => [
        'id', 'name', 'featuredImage', 'url', 'publishDate', 'blogAuthorId', 'tagIds', 'postBody',
      ],
    ];
    
    $page = $hubspot->cms()->blogs()->blogPosts()->blogPostApi()->getPage($settings);
    
    $result = [
      'meta' => [
        'total' => $page->getTotal(),
        'offset' => $settings['offset'],
        'limit' => $settings['limit'],
        'pages' => $limit > 0 ? ceil($page->getTotal() / $limit) : 1,
        'page' => $_page,
      ],
      'data' => $page->getResults(),
    ];
    
    
```

**Comment by psjavi** [comment]
> ```
>     $settings = [
>       'content_group_id' => [YOUR BLOG ID],
>       'offset' => 1,
>       'limit' => 2,
>       'state' => 'PUBLISHED',
>       'sort' => '-publish_date',
>       'property'  => [
>         'id', 'name', 'featuredImage', 'url', 'publishDate', 'blogAuthorId', 'tagIds', 'postBody',
>       ],
>     ];
>     
>     $page = $hubspot->cms()->blogs()->blogPosts()->blogPostApi()->getPage($settings);
>     
>     $result = [
>       'meta' => [
>         'total' => $page->getTotal(),
>         'offset' => $settings['offset'],
>         'limit' => $settings['limit'],
>         'pages' => $limit > 0 ? ceil($page->getTotal() / $limit) : 1,
>         'page' => $_page,
>       ],
>       'data' => $page->getResults(),
>     ];
>     
>     
> ```

No luck, I'm getting the following error:

`{"correlationId":"82cf4ac0-764d-4f8d-ac3d-69c9b09f0c26","message":"Invalid input JSON on line -1, column -1: Cannot deserialize value of type `com.hubspot.apiutils.core.models.time.Iso8601Instant` from Array value (token `JsonToken.START_ARRAY`)","status":"error"}`

By the way, I'm using the following version: 10.1.0

**Comment by ksvirkou-hubspot** [comment]
Hi @psjavi .
Filters for Blog posts API are not supported in the SDK.
But you can get it by apiRequest method
Workable example:
```php 
$hubspot = Factory::createWithAccessToken('***');

$response = $hubspot->apiRequest([
  'path' => '/cms/v3/blogs/posts',
  'qs' => ['state' => 'PUBLISHED'],
]);

var_dump($response->getBody()->getContents());
```

**Comment by psjavi** [comment]
Thanks for your response @ksvirkou-hubspot 

Are you going to improve the current method in order to be able to do filters?

**Comment by ksvirkou-hubspot** [comment]
The SDK is auto-generated based on swagger files and filter mechanism (in current state) is impossible to add to the SDK.
Maybe in future something changed and it will add to the SDK.
