### ISSUE TITLE
Add documentation for custom behavioral events

### ISSUE THREAD

**Issue by chris-chalmers** [HubSpot/hubspot-api-php#267]
I see there are classes for events but I can't tell of they are for Hubspot API Custom Behavioral Events (https://developers.hubspot.com/docs/api/analytics/events) or some other kind of event. Please add documentation for these with examples in the readme( https://github.com/HubSpot/hubspot-api-php#readme). I'd like to make the same request for Knowledge Base articles and Support tickets as they become available. Thanks!

**Comment by ksvirkou-hubspot** [comment]
Hi @chris-chalmers .
Now [Custom Behavioral Events](https://developers.hubspot.com/docs/api/analytics/events) have not beed added to the SDK, because the API is under development.
When it's in beta, It will be add to the SDK.

**Comment by ksvirkou-hubspot** [comment]
Yes, I still can't added it.

**Comment by ksvirkou-hubspot** [comment]
I've added it in [10.3.0](https://packagist.org/packages/hubspot/api-client#10.3.0).

**Comment by ksvirkou-hubspot** [comment]
The method takes a required argument - object ([BehavioralEventHttpCompletionRequest](https://github.com/HubSpot/hubspot-api-php/blob/master/codegen/Events/Send/Model/BehavioralEventHttpCompletionRequest.php)).
