### ISSUE TITLE
Create or update a group of contacts

### ISSUE THREAD

**Issue by AhmedAliGad** [HubSpot/hubspot-api-php#272]
I need to Create or update a group of contacts
any documentation help me

**Comment by ksvirkou-hubspot** [comment]
Hi @AhmedAliGad .
You can use `$client->crm()->contacts()->batchApi()` for CRUD operations with group of contacts.
Create a group of contacts: `$apiResponse = $client->crm()->contacts()->batchApi()->create()`.
Create a group of contacts: `$apiResponse = $client->crm()->contacts()->batchApi()->update()`.
[Link to docs for these methods.](https://developers.hubspot.com/docs/api/crm/contacts)

**Comment by AhmedAliGad** [comment]
I need to update the contact data if the contact email exists 
or create the contact data if not exists

**Comment by ksvirkou-hubspot** [comment]
Currently Hubspot doesn't support method which could do it.
You can check if contacts exist and that update or create them.
