### ISSUE TITLE
Call to undefined function GuzzleHttp\json_encode()

### ISSUE THREAD

**Issue by thelonewolf** [HubSpot/hubspot-api-php#274]
PHP 8.1.13
HubSpot API PHP 10.1.0
Guzzle 7.8.0

When following the documentation here https://developers.hubspot.com/docs/api/crm/contacts to search for a contact by email address I was getting the following:

**_Fatal error: Call to undefined function GuzzleHttp\json_encode() in /vendor/hubspot/api-client/codegen/Crm/Contacts/Api/SearchApi.php:362_**

On line 362, if I replace `$httpBody = \GuzzleHttp\json_encode` with `$httpBody = \GuzzleHttp\Utils::jsonEncode` the error goes away and everything works as it should.

Also getting this error here vendor/hubspot/api-client/codegen/Crm/Contacts/Api/BasicApi.php:608 & vendor/hubspot/api-client/codegen/Crm/Contacts/Api/BasicApi.php:1696

So looks like a code base wide update from  \GuzzleHttp\json_encode to  \GuzzleHttp\Utils::jsonEncode is needed. Hope that helps.

**Comment by ksvirkou-hubspot** [comment]
Hi @thelonewolf .
I can't reproduce this error.
My code(works correctly):
```php
use HubSpot\Factory;
use HubSpot\Client\Crm\Contacts\Model\Filter;
use HubSpot\Client\Crm\Contacts\Model\FilterGroup;
use HubSpot\Client\Crm\Contacts\Model\PublicObjectSearchRequest;

$hubspot = Factory::createWithAccessToken('private app access token');

$filter = new Filter([
  'value' => 'example@example.com',
  'property_name' => 'email',
  'operator' => 'EQ'
]);
$filterGroup = new FilterGroup(['filters' => [$filter]]);
$request = new PublicObjectSearchRequest([ 'filter_groups' => [$filterGroup]]);

$response = $hubspot->crm()->contacts()->searchApi()->doSearch($request);

var_dump($response);
```
PHP 8.1.13
HubSpot API PHP 10.1.0
Guzzle 7.8.0
