### ISSUE TITLE
Create company is empty

### ISSUE THREAD

**Issue by struyfv** [HubSpot/hubspot-api-php#291]
Hi,

When I create a company with $this->client->crm()->companies()->basicApi()->create($simplePublicObjectInputForCreate); it creates an empty company in Hubspot. 

When I try it here https://developers.hubspot.com/docs/api/crm/companies, it works. I have copy paste the exact code from there but in my project it doesn't work.

Any idea?

**Comment by ksvirkou-hubspot** [comment]
Hi @struyfv 
You need to pass to `$simplePublicObjectInputForCreate` new empty object of `SimplePublicObjectInputForCreate` class.
Workable example:
```php
use HubSpot\Factory;
use HubSpot\Client\Crm\Companies\Model\SimplePublicObjectInputForCreate;

$hubspot = Factory::createWithAccessToken($_ENV['HUBSPOT_PRIVATE_APP_ACCESS_TOKEN']);


$response = $hubspot->crm()->companies()->basicApi()->create(new SimplePublicObjectInputForCreate());

var_dump($response);
```

**Comment by struyfv** [comment]
@ksvirkou-hubspot 
I found the error.  I used
use Hubspot\Client\Crm\**Contacts**\Model\SimplePublicObjectInputForCreate (because I also create a contact in the same file)
instead of 
use HubSpot\Client\Crm\**Companies**\Model\SimplePublicObjectInputForCreate;
