### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by Vesninandrey** [HubSpot/hubspot-api-php#3]
Hi! Is there any chance that this repo will have semantic versioning?

**Comment by yfaktor** [comment]
hi @Vesninandrey  - so the package in packagist (hubspot/api-client) does have semver. As to this repo, we will be bumping version in https://github.com/HubSpot/hubspot-api-php/blob/master/composer.json and make it SemVer compliant - is that what you had in mind? Thanks

**Comment by Vesninandrey** [comment]
Yep, thx!
