### ISSUE TITLE
Cannot define objectType in event API

### ISSUE THREAD

**Issue by tomsommer** [HubSpot/hubspot-api-php#361]
Using the `customEventDataApi()` it's not possible to define `objectType` in `BehavioralEventHttpCompletionRequest`

Reference: https://developers.hubspot.com/docs/api/analytics/events

**Comment by ksvirkou-hubspot** [comment]
Hi @tomsommer 
`objectType` no need in `BehavioralEventHttpCompletionRequest`
`objectType` was mention in the docs by mistake.
We have updated the docs.
