### ISSUE TITLE
do not use "access-token" as default token (as this token exists)

### ISSUE THREAD

**Issue by odoucet** [HubSpot/hubspot-api-php#363]
I lost several hours of debugging on my code, because I was still using "access-token" as token used and the error message was : 
```
The OAuth token used to make this call expired 19884 day(s) ago.
```

This was very confusing because I thought this was an issue with my token.

If you try to use token "thisisatesttoken", the error is 
```
Authentication credentials not found.
```
This error message makes more sense.
So please, dont use "access-token" in documentation.

**Comment by ksvirkou-hubspot** [comment]
Hi @odoucet 
Do you mean [the README](https://github.com/HubSpot/hubspot-api-php/blob/master/README.md) or the other documentation?

**Comment by odoucet** [comment]
the README file :)

**Comment by ksvirkou-hubspot** [comment]
Done
Thank you for reporting the issue.
