### ISSUE TITLE
Why email not delivered using single-send-api?

### ISSUE THREAD

**Issue by pragna-php** [HubSpot/hubspot-api-php#368]
Hello everyone,

Using [this](https://api.hubapi.com/marketing/v4/email/single-send) API I am getting sent status but it is not actually delivering the email to the email address. 

Can anyone please provide solution to my query because as per my knowledge it should be delivered to the inbox of the email address.

Any help would be really appreciated. Thank you in advance!

**Comment by pragna-php** [comment]
Hello @all

Please let me know if anyone has any idea related to this.

Thanks

**Comment by atanasiuk-hubspot** [comment]
Hey @pragna-php, could you please provide a payload and response body for the request?

**Comment by ksvirkou-hubspot** [comment]
Hey @pragna-php
Have you checked SPAM?

**Comment by tarang-tops** [comment]
I am creating email template using mareketing api and while perform the single send api at that time given below error 
 "requiredScopes": [
    "marketing-email",
    "transactional-email"
]

I am use simple account without any premium and while try to enable scope checkbox is disable and showing tooltip like "Your account doesn't have access to this scope.".

**Comment by pragna-php** [comment]
Hello @ksvirkou-hubspot @atanasiuk-hubspot , Thank you for your reply !

Here is the required steps:
1. Create custom template
2. Save template as Email
3. Send email using single-send-api

In these steps, I am sharing apis, request and response all. so that in between any issue then I can get suggestion. The thing is 3rd API throwing error of missing scope that actually their in my private app. Please check below and let me know what is the exact issue. Also Is it require to upgrade the account as I am using free demo account. 

1. Create custom template
![image](https://github.com/user-attachments/assets/c2bf9ba0-cc44-4f87-9ec0-78803b821da6)

2. Save template as Email
![image](https://github.com/user-attachments/assets/6eea7356-c88e-4558-9594-7858a1dc76d2)

3. Send email using single-send-api
![image](https://github.com/user-attachments/assets/65a986f4-265b-4069-b349-2258000e3010)

Here in below screenshot is the application scoped which has available scope
![image](https://github.com/user-attachments/assets/0a569e10-85d1-4abf-8fbb-4f8622818170)


I tried very hard to achieve the same but in 3rd step getting the issue. Please let me know if anything missing or wrong in above

**Comment by ksvirkou-hubspot** [comment]
> I am creating email template using mareketing api and while perform the single send api at that time given below error "requiredScopes": [ "marketing-email", "transactional-email" ]
> 
> I am use simple account without any premium and while try to enable scope checkbox is disable and showing tooltip like "Your account doesn't have access to this scope.".

[You must have a Marketing Hub Enterprise account](https://developers.hubspot.com/docs/api/marketing/single-send-api#requirements), otherwise, you won't be able to use it.

**Comment by ksvirkou-hubspot** [comment]
> Hello @ksvirkou-hubspot @atanasiuk-hubspot , Thank you for your reply !
> 
> Here is the required steps:
> 
> 1. Create custom template
> 2. Save template as Email
> 3. Send email using single-send-api
> 
> In these steps, I am sharing apis, request and response all. so that in between any issue then I can get suggestion. The thing is 3rd API throwing error of missing scope that actually their in my private app. Please check below and let me know what is the exact issue. Also Is it require to upgrade the account as I am using free demo account.
> 
> 1. Create custom template
>    ![image](https://private-user-images.githubusercontent.com/175293465/356186268-c2bf9ba0-cc44-4f87-9ec0-78803b821da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU3NjgsIm5iZiI6MTcyMzExNTQ2OCwicGF0aCI6Ii8xNzUyOTM0NjUvMzU2MTg2MjY4LWMyYmY5YmEwLWNjNDQtNGY4Ny05ZWMwLTc4ODAzYjgyMWRhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNiYWQzN2MwNWI1NjkzMWI5MjYyODEzOTM1Njg2NzAwYjQxN2Y5YzcwYzQ5MzdmMjczZDQ4M2FmZWJiNDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-kb4Sf2cW-i19ittrQP2gqek4uAf3pPkuT2qB9MRKYs)
> 2. Save template as Email
>    ![image](https://private-user-images.githubusercontent.com/175293465/356186688-6eea7356-c88e-4558-9594-7858a1dc76d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU3NjgsIm5iZiI6MTcyMzExNTQ2OCwicGF0aCI6Ii8xNzUyOTM0NjUvMzU2MTg2Njg4LTZlZWE3MzU2LWM4OGUtNDU1OC05NTk0LTc4NThhMWRjNzZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzc3MGU1OTY5OWIyMjBmNTAxMTc1M2ViMTUxNDQyMWVkZmRmOGRmZTVlMWE5YWNkZTAxODJmNWQxN2RiZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OdIwDJFIwslb8KaBXzNNsgFggaVdGTW6lsM_r63FEtg)
> 3. Send email using single-send-api
>    ![image](https://private-user-images.githubusercontent.com/175293465/356187060-65a986f4-265b-4069-b349-2258000e3010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU3NjgsIm5iZiI6MTcyMzExNTQ2OCwicGF0aCI6Ii8xNzUyOTM0NjUvMzU2MTg3MDYwLTY1YTk4NmY0LTI2NWItNDA2OS1iMzQ5LTIyNTgwMDBlMzAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDQwYTZkNzU4ZGU1NjVhNzRhMmI3MzA0NDZhNDEwMzUwM2JiZTQxMjA0ZjZhNWExNjhiY2QyMTg5YjIwMTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RPz3lydABI58h0kN17DTAtSfKy-G4-AqKaOXznpDVPQ)
> 
> Here in below screenshot is the application scoped which has available scope ![image](https://private-user-images.githubusercontent.com/175293465/356187422-0a569e10-85d1-4abf-8fbb-4f8622818170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU3NjgsIm5iZiI6MTcyMzExNTQ2OCwicGF0aCI6Ii8xNzUyOTM0NjUvMzU2MTg3NDIyLTBhNTY5ZTEwLTg1ZDEtNGFiZi04ZmJiLTRmODYyMjgxODE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzg2YmY0MTRjYjY3MzE5ZjA0MTg5OWZiNDFhMTQzYTZmNzIwMzI5OTRlZWE5NzE1NmRhMGQ1ZmU5ZTc5ODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L6U8SsU7B57NxK0xy_6TTuiPBXZO-x5joNSO8QxNUVw)
> 
> I tried very hard to achieve the same but in 3rd step getting the issue. Please let me know if anything missing or wrong in above

Try to send the same request to `POST https://api.hubapi.com/marketing/v4/email/single-send`.

**Comment by pragna-php** [comment]
Yes tried "https://api.hubapi.com/marketing/v4/email/single-send" this api but getting 404
![image](https://github.com/user-attachments/assets/f1555d5d-976a-4823-8a59-b315d201129a)

**Comment by ksvirkou-hubspot** [comment]
<img width="702" alt="Снимок экрана 2024-08-08 в 14 32 56" src="https://github.com/user-attachments/assets/adee3e0d-06e1-4fc2-b3d0-e3087fb0f665">

**Comment by tarang-tops** [comment]
> <img alt="Снимок экрана 2024-08-08 в 14 32 56" width="702" src="https://private-user-images.githubusercontent.com/57258237/356204943-adee3e0d-06e1-4fc2-b3d0-e3087fb0f665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTc3MjEsIm5iZiI6MTcyMzExNzQyMSwicGF0aCI6Ii81NzI1ODIzNy8zNTYyMDQ5NDMtYWRlZTNlMGQtMDZlMS00ZmMyLWIzZDAtZTMwODdmYjBmNjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTIzODMzZTM4NTI2MmI2ZDk3NGYwMzVjMDIxMjJmMzYzYzFkZTkxMmMzZjFjYzZjNTc2ZTRkOWQzNDA5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_KUA15BhX6mJxKwbdNLhX-yAJ7nnICLnG5Jm2jRBGk">

have you premium account?

**Comment by ksvirkou-hubspot** [comment]
What is premium account?
I have subscription - Marketing Hub Enterprise

**Comment by pragna-php** [comment]
Got it @ksvirkou-hubspot 
Once I upgrade my account then after the issue get fixed. 
Thank you so much for your replies and support. I really appreciate this. Thank you !

**Comment by ksvirkou-hubspot** [comment]
> Got it @ksvirkou-hubspot Once I upgrade my account then after the issue get fixed. Thank you so much for your replies and support. I really appreciate this. Thank you !

Do you have any subscription now?

**Comment by pragna-php** [comment]
Not yet but shortly will get and test again this api.

**Comment by ksvirkou-hubspot** [comment]
Feel free to reopen it if you have any questions/other errors.
