### ISSUE TITLE
Missing hte CRM Leads object

### ISSUE THREAD

**Issue by 12Build** [HubSpot/hubspot-api-php#369]
Hi, it would be really nice if the [Leads](https://developers.hubspot.com/beta-docs/reference/api/crm/objects/leads/v3?uuid=2130dbe5-af07-466a-aa08-50dc3ff9b0a0) object would also be available, just like the Deals object.

**Comment by ksvirkou-hubspot** [comment]
Hi @12Build  
I've just published it  in version [11.2.0](https://packagist.org/packages/hubspot/api-client#11.2.0).
