### ISSUE TITLE
Missing the 'upsert' functionality from API docs

### ISSUE THREAD

**Issue by jonom** [HubSpot/hubspot-api-php#370]
The contact 'upsert' feature outlined for the V3 API isn't available in this SDK, and the code sample on the beta docs site is broken as a result. https://developers.hubspot.com/beta-docs/reference/api/crm/objects/contacts#post-%2Fcrm%2Fv3%2Fobjects%2Fcontacts%2Fbatch%2Fupsert

**Comment by ksvirkou-hubspot** [comment]
Hi @DanFaudemer
"upsert" methods have beed added [in the latest version of the SDK](https://packagist.org/packages/hubspot/api-client#12.0.0).
