### ISSUE TITLE
Creating Leads: Sample code from  documentation does not work

### ISSUE THREAD

**Issue by harpreetsb** [HubSpot/hubspot-api-php#371]
Hi,
We are using PHP to create contacts and leads in hubspot.
Though the contact was created with sample code easily
I am trying to create a lead from a contact. 
I used the sample code from [page](https://developers.hubspot.com/docs/api/crm/leads) 
the code used is:
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.hubapi.com/crm/v3/objects/leads",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\"associations\":[{\"types\":[{\"associationCategory\":\"HUBSPOT_DEFINED\",\"associationTypeId\":0}],\"to\":{\"id\":\"string\"}}],\"properties\":{\"additionalProp1\":\"string\",\"additionalProp2\":\"string\",\"additionalProp3\":\"string\"}}",
  CURLOPT_HTTPHEADER => array(
    "accept: application/json",
    "authorization: Bearer YOUR_ACCESS_TOKEN",
    "content-type: application/json"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

The response I get is:

> {
>   "status": "error",
>   "message": "This app hasn't been granted all required scopes to make this call. Read more about required scopes here: https://developers.hubspot.com/scopes.",
>   "correlationId": "1b86b036-0843-4ec5-bbb7-ad51eeb4bfea",
>   "errors": [
>     {
>       "message": "One or more of the following scopes are required.",
>       "context": {
>         "requiredGranularScopes": [
>           "crm.objects.leads.write"
>         ]
>       }
>     }
>   ],
>   "links": {
>     "scopes": "https://developers.hubspot.com/scopes"
>   },
>   "category": "MISSING_SCOPES"
> }

Attached is the screenshot from the scopes in created app
![image](https://github.com/user-attachments/assets/405f9c9d-bd35-4e2c-adcd-812c22914d51)

Please help

**Comment by harpreetsb** [comment]
UPDATE:
PHP 8.2

**Comment by justingivens** [comment]
@harpreetsb it could be a couple of things.

- Check the scope off your access_token against the [oauth endpoint](https://developers.hubspot.com/beta-docs/reference/api/oauth#get-information-for-oauth-2.0-access-token).
- Try re-connecting the app through OAUTH again to get a new access_token.
- If this is a private app, ensure you're using the correct Private Key with the correct scope. Again you can check the scopes against the oauth endpoint above.

Randomly noticed that you didn't have the correct AssocationTypeID in your data.  

This also isn't related to the PHP SDK. 

If you need additional assistance with the API in general, I'd recommend connecting on the (HubSpot Developer Slack Community](https://developers.hubspot.com/slack)

**Comment by ksvirkou-hubspot** [comment]
Hi @harpreetsb 
You must have Sales Hub Professional subscription, otherwise, you won't be able to use it.
Do you have Sales Hub Professional subscription?
