### ISSUE TITLE
Contacts api: Not getting phone field

### ISSUE THREAD

**Issue by pragna-php** [HubSpot/hubspot-api-php#372]
Hello, 

Below is the reference code and using same and even using the core apis, I am not able to get the phone field which is default in the contact form of hubspot.

`$ContactResponse = $this->hubSpot->crm()->contacts()->basicApi()->getById($contact['id'], ['firstname','lastname','email','preferences','phone']);`

Can anyone please help? as this is the default property and it should be available as first name and other properties which are default.

Thank you in advance! Any help would be appreciated.

**Comment by justingivens** [comment]
What PHP version or SDK version are you using?

**Comment by justingivens** [comment]
The SDK is working for me. 

```
$contact = $hubspot->crm()->contacts()->basicApi()->getById("1411201", [
    'firstname',
    'lastname',
    'preferences',
    'hs_analytics_first_url',
    'phone'
]);
```

**Comment by pragna-php** [comment]
Issue Fixed! Thank you for your reply @justingivens
