### ISSUE TITLE
'Create Table' does not work according to documentation

### ISSUE THREAD

**Issue by badererliebert** [HubSpot/hubspot-api-php#373]
I'm using the Hubspot PHP class to send a CreateTable request, and getting back a non-descriptive error that sounds like an unhandled exception. Please find attached screenshots of my code, and the error message I'm getting back. You can see the logs confirming that my class & authentication is properly instantiated by using a different class method to read back the table names. I think this is a bug.
![Screenshot 2024-07-25 100602](https://github.com/user-attachments/assets/75f5e316-fc19-4d64-8993-8267264bc47f)
![Screenshot 2024-07-25 101159](https://github.com/user-attachments/assets/e004eafc-b365-4018-9e44-af019c3f1b39)

**Comment by justingivens** [comment]
Hey @badererliebert 

There's an issue with the SDK where it's saying you need to pass in an array for `dynamic_meta_tags` but the API wants an object. 

Since you aren't using dynamic tags, update your code to the following:

```
$response = $hubDbTableV3Request = new HubDbTableV3Request([
    'dynamic_meta_tags' => new \stdClass(),
    'allow_public_api_access' => false,
    'use_for_pages' => true,
    'columns' => [ $columns ],
    'name' => 'test_table',
    'enable_child_table_pages' => false,
    'label' => 'Test Table',
    'allow_child_tables' => true
]);```

That should fix it. 

Also, `status` is not valid. You need to call the publishDraft Table after you get the ID.

```
$hubspot->cms()->hubdb()->tablesApi()->publishDraftTable($response->getId());
```

Let me know if you have any other questions or issues.

**Comment by justingivens** [comment]
@badererliebert, yes, I noticed that as well. I'm trying to get the team to correct it. 

Disclaimer: I do not work for HubSpot.

**Comment by badererliebert** [comment]
> @badererliebert, yes, I noticed that as well. I'm trying to get the team to correct it.
> 
> Disclaimer: I do not work for HubSpot.

Thanks Justin. So do you know who authored this package and is responsible for ongoing maintenance? Do you have an active role in this or are you a knowledgeable and concerned onlooker? I'm putting it into production in an enterprise environment and trying to get to the bottom of the maintainability question. Not trying to come off as challenging, but just trying to get clarity on the infrastructure. I appreciate your stepping in we've been blocked on this for over a week.

**Comment by justingivens** [comment]
@badererliebert I'm working to find those same questions out, I'm just an outsider helping.
