### ISSUE TITLE
Leads support is missing?

### ISSUE THREAD

**Issue by Modelizer** [HubSpot/hubspot-api-php#375]
It is a bit difficult to understand how to utilize leads from the API client package. Nor, leads documentation is mentioned here: https://developers.hubspot.com/docs/api/crm/understanding-the-crm

If we go to https://developers.hubspot.com/docs/api/crm/leads leads documentation, it isn't clear enough how we can utilise in PHP package. For example, if we want to make a deal we use the code below
```php
app(HubSpot\Discovery\Discovery::class)
    ->crm()
    ->deals()
    ->basicApi()
    ->create(
        new SimplePublicObjectInputForCreate($data)
    );
```

We aren't sure how we can do something similar with leads?

**Comment by Modelizer** [comment]
thanks! @atanasiuk-hubspot and @ksvirkou-hubspot, could you please keep me updated via this issue when the new version is released?

**Comment by ksvirkou-hubspot** [comment]
Hi @Modelizer 
I've just published it  in version [11.2.0](https://packagist.org/packages/hubspot/api-client#11.2.0).

**Comment by Modelizer** [comment]
Thank you @ksvirkou-hubspot.

Although I notice enum times https://developers.hubspot.com/docs/api/crm/associations#lead-to-object for leads are missing from https://github.com/HubSpot/hubspot-api-php/blob/master/lib/Enums/AssociationTypes.php ?

**Comment by ksvirkou-hubspot** [comment]
https://packagist.org/packages/hubspot/api-client#11.3.0
