### ISSUE TITLE
Documentation seems to be wrong/outdated

### ISSUE THREAD

**Issue by PascalKremp** [HubSpot/hubspot-api-php#384]
Example of https://developers.hubspot.com/docs/api/cms/pages

```
<?php
use HubSpot\Factory;
use HubSpot\Client\Cms\Pages\SitePages\ApiException;

$client = Factory::createWithAccessToken('YOUR_ACCESS_TOKEN');

try {
    $apiResponse = $client->cms()->pages()->sitePages()->sitePagesApi()->getById('objectId');
    var_dump($apiResponse);
} catch (ApiException $e) {
    echo "Exception when calling site_pages_api->get_by_id: ", $e->getMessage();
}
```

Needs to be

```
$apiResponse = $client->cms()->pages()->sitePagesApi()->getById($'objectId);
```

Couple of PHP Examples are very outdated.

I think there is no sync process between the code and the documentation?

**Comment by ksvirkou-hubspot** [comment]
Hi @PascalKremp 
I have fixed CMS Pages code examples.
We published SDK 12.0.0 and I think the most code examples are be relevant now.
If you find outdated code example, please share it with us.
