### ISSUE TITLE
Get Properties from the Associations - php

### ISSUE THREAD

**Issue by meigieong** [HubSpot/hubspot-api-php#39]
How to get the properties from the associations? The results only return id and type, where I need the full properties of the type. For example, contacts, how to return email, firstname, lastname and etc as associations?

I tried below and managed to get associationsApi() but then cannot get().
`$hubSpot` = Factory::createWithApiKey($apiKey);
`$response` = $hubSpot->crm()->deals()->associationsApi();

also possible to get the deals from a selected pipeline?

**Comment by atanasiuk-hubspot** [comment]
Hi, @meigieong, I think it's not possible to fetch more properties via `associations` API. You should be able to request `contacts` API additionally.

**Comment by meigieong** [comment]
hi @atanasiuk-hubspot! so the library only supports calling the API individually? like request `Contacts` only, `Deals` only, `Companies` only.

how about getting the deals from a selected pipeline?

**Comment by atanasiuk-hubspot** [comment]
> so the library only supports calling the API individually? like request `Contacts` only, `Deals` only, `Companies` only.

The library is 1:1 to [API](https://developers.hubspot.com/docs/api/crm/contacts).

**Comment by meigieong** [comment]
got it. thanks!
