### ISSUE TITLE
How to associate my ID with the user ID from hubspot?

### ISSUE THREAD

**Issue by RodrigoGalter** [HubSpot/hubspot-api-php#4]
I wanted to associate my user ID with hubspot ID, for future better identification.

**Comment by zman81988** [comment]
Hey @RodrigoGalter I'm not sure I fully understand what you are looking to do. Can you maybe provide an example?

**Comment by RodrigoGalter** [comment]
Hello, follow an example.
On my system the user has ID 10, when I send it to HubSpot, it returns me an ID 200 for example.
I wanted a way to tell HubSpot that id 200 for me is 10, or use my ID for id in HubSpot.

Thank you.

**Comment by zman81988** [comment]
That makes sense thank you for clarifying. Allowing you to use your own ID is something we have planned but haven't done yet.  I don't have a timeline for you but it is coming. Thanks for the feedback!

**Comment by yfaktor** [comment]
Closing this as we don't have a solution yet  for this but it is on the roadmap - please feel free to reopen
