### ISSUE TITLE
How to set the BatchInputPublicObjectId for Associations

### ISSUE THREAD

**Issue by speedwheel** [HubSpot/hubspot-api-php#40]
I am trying to send with postman the correct request for calling the Batch API Read for Associations, here is my code:

```
$associationRequest = new \HubSpot\Client\Crm\Associations\Model\BatchInputPublicObjectId();
  $id = new \HubSpot\Client\Crm\Associations\Model\PublicObjectId;
  $associationRequest->setInputs($id->setId("4324519850"));
  $associationsObj = $hubspot->crm()->associations()->batchApi()->read("deals", "line_items", $associationRequest)->getResults();
```
And in Postman I am sending a POST request with x-www-form-urlencoded request with `id:4324519850` (the id of the deal)

But I get an error:
` resulted in a `400 Bad Request` response:\n{\"status\":\"error\",\"message\":\"Invalid input JSON on line 1, column 11: Cannot deserialize instance of `java.util.ArrayLis (truncated...)\n"`

Any thoughts?

**Comment by speedwheel** [comment]
I've managed to find a solution, here is my code:
```$associationRequest = new \HubSpot\Client\Crm\Associations\Model\BatchInputPublicObjectId();
            $id[0] = new \HubSpot\Client\Crm\Associations\Model\PublicObjectId;
            $id[0]->setId("4324519850");
            $associationRequest->setInputs($id);
            $associationsObj = $hubspot->crm()->associations()->batchApi()->read("deals", "line_items", $associationRequest)->getResults();
            $associations = [];
            
            foreach ($associationsObj as $i => $association) {
                $associations["from"][] =  $association->getFrom()->getId();
                foreach ($association->getTo() as $j => $getTo) {
                    $associations["to"][] = $getTo->getId();
                }
            }```

Is this the way?

**Comment by tominal** [comment]
Is this documented anywhere? Somehow I ended up in the issues section to figure out what I was doing wrong.

**Comment by jumpCircuit** [comment]
I also landed on this issue by following the Hubspot code examples.

I hope the remainder of my comment shows up in someone's search query.

https://developers.hubspot.com/docs/api/crm/associations
syntax error from docs:
`$BatchInputPublicObjectId = new BatchInputPublicObjectId(['inputs' => [{"id":"37295"}]]);`

**Comment by ksvirkou-hubspot** [comment]
I ve just fixed it 
https://developers.hubspot.com/docs/api/crm/associations/v3
