### ISSUE TITLE
How To Get Next Page of the Deals That Have More Than 100?

### ISSUE THREAD

**Issue by meigieong** [HubSpot/hubspot-api-php#41]
I found there are models call Paging, NextPage, PreviousPage but how can we use them?

I can get the deal results with the below but I need to get the rest, after the 100th record.

`$response = $hubSpot->crm()->deals()->searchApi()->doSearch($searchRequest);`

Kindly advice.

**Comment by ksvirkou-hubspot** [comment]
Hi @meigieong 

`
        $after = null;
        $request = new \HubSpot\Client\Crm\Deals\Model\PublicObjectSearchRequest(['query' => $query]);
        $request->setLimit(100);

        do {
            $request->setAfter($after);
            $objects = $hubspot->crm()->deals()->searchApi()->doSearch($request);

            var_dump($objects->getResults());
            if ($objects->getPaging()) {
                $after = $objects->getPaging()->getNext()->getAfter();
            } else {
                $after = null;
            }
        } while ($after);
`
and you can check [this sample](https://github.com/HubSpot/sample-apps-manage-crm-objects/blob/main/php/src/Commands/Objects/GetCommand.php)

Best Regards

**Comment by meigieong** [comment]
thanks!
