### ISSUE TITLE
`ArrayAccess` implementations dockblocks are incorrect

### ISSUE THREAD

**Issue by markwalet** [HubSpot/hubspot-api-php#45]
The classes that implement the `ArrayAccess` interface in the `codegen` folder have incorrect type hinting in their docblocks.

It implies that the keys of `$this->container` are integers. But they are actually strings.

Example:

```
/**
 * Returns true if offset exists. False otherwise.
 *
 * @param integer $offset Offset
 *
 * @return boolean
 */
public function offsetExists($offset)
{
    return isset($this->container[$offset]);
}
```

Should be:

```
/**
 * Returns true if offset exists. False otherwise.
 *
 * @param string $offset Offset
 *
 * @return boolean
 */
public function offsetExists($offset)
{
    return isset($this->container[$offset]);
}
```

I don't know how the `codegen` folder is generated, so I can't do it for you unfortunately.

**Comment by ksvirkou-hubspot** [comment]
$offset have to be integer type or it can be string which could be convertible to integer.
