### ISSUE TITLE
Company Default properties and address is missing

### ISSUE THREAD

**Issue by avantassel** [HubSpot/hubspot-api-php#47]
Why are default properties missing from the company object?

```HubSpot\\Client\\Crm\\Companies\\Model\\SimplePublicObject::__set_state(array(\n   'container' => \n  array (\n    'id' => '6069095424',\n    'properties' => \n    array (\n      'createdate' => '2021-05-13T18:31:59.188Z',\n      'domain' => 'brewbench.co',\n      'hs_lastmodifieddate' => '2021-05-25T03:42:18.135Z',\n      'hs_object_id' => '6069095424',\n      'name' => 'BrewBench',\n    ),\n    'created_at' => \n    DateTime::__set_state(array(\n       'date' => '2021-05-13 18:31:59.188000',\n       'timezone_type' => 2,\n       'timezone' => 'Z',\n    )),\n    'updated_at' => \n    DateTime::__set_state(array(\n       'date' => '2021-05-25 03:42:18.135000',\n       'timezone_type' => 2,\n       'timezone' => 'Z',\n    )),\n    'associations' => NULL,\n    'archived' => false,\n    'archived_at' => NULL,\n  ),\n))```

**Comment by ksvirkou-hubspot** [comment]
Hi @avantassel 
Could you check it on [new version](https://github.com/HubSpot/hubspot-api-php/releases/tag/3.0.2) ?
