### ISSUE TITLE
Incorrect $attributeMap in BlogPost model

### ISSUE THREAD

**Issue by andrewi-wd** [HubSpot/hubspot-api-php#48]
```
\HubSpot\Client\Cms\Blogs\BlogPosts\Model\BlogPost::$attributeMap = [
    ...,
    'created_at' => 'createdAt',
    'updated_at' => 'updatedAt',
    ...
]
```

While provided attributes are missing from actual API response body. It has `updated` and `created` instead.

**Comment by ksvirkou-hubspot** [comment]
Hi @andrewi-wd 
Could you check it on [new version](https://github.com/HubSpot/hubspot-api-php/releases/tag/3.0.2) ?
