### ISSUE TITLE
createTableRow() returns protected object

### ISSUE THREAD

**Issue by PeteDMS** [HubSpot/hubspot-api-php#49]
When calling Cms()->Hubdb()->rowsApi()->createTableRow(), the response from HubSpot (containing the created row ID etc), is returned as a HubDbTableRowV3 object, which is a protected container and can't be parsed. First time I've had this with a method and can't see any other methods to call instead.

**Comment by ksvirkou-hubspot** [comment]
Hi  @PeteDMS 
Could you check it on [new version](https://github.com/HubSpot/hubspot-api-php/releases/tag/3.0.2) or share example of code?

**Comment by PeteDMS** [comment]
Hi @ksvirkou-hubspot 
I am now able to parse the response, thanks!
Has anything changed on Cms()->Hubdb()->rowsApi()->getTableRows()? All values now seem to be returned in an array regardless of column types (strings/numbers included). E.g.

What used to be:

"stringcol" => "string",
"intcol" => 1234,

Is now:

"stringcol" => [ 0 => "string" ],
"intcol" => [ 0 => 1234 ],

Map type columns still seem to be working as before, just everything else.

**Comment by ksvirkou-hubspot** [comment]
yes it was changed but what exactly was changed I can't say

**Comment by PeteDMS** [comment]
Are there any plans to change back or should I update my code?
