### ISSUE TITLE
Possible nullables in object chains contradict the idea of fluent interfaces

### ISSUE THREAD

**Issue by alexanderschnitzler** [HubSpot/hubspot-api-php#5]
Hi folks,

I am using your new client to fetch data and in theory it's great to be able to chain all the calls, such as the following.

```php
/** @var \HubSpot\Client\Crm\Contacts\Model\CollectionResponseAssociatedId $deals */
$deals->getPaging()->getNext()
```

https://github.com/HubSpot/hubspot-api-php/blob/b80c1943be91ab8a80eecdee907b8e4a9bd893be/codegen/Crm/Contacts/Model/CollectionResponseAssociatedId.php#L243

Method `getPaging()` possibly returns `null`, which contradicts the idea of fluent interfaces. If you worked with NullObjects e.g. instead, it would make much more sense but this way I have to type check all the method results before knowing if I can actually chain them without causing a NullPointerException.

Is there anything planned to make the client more type safe?

**Comment by atanasiuk-hubspot** [comment]
Hi, @alexanderschnitzler,

Thank you for your feedback, sounds reasonable to me. 

The difficult is that SDK uses [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) to auto-generate clients (\HubSpot\Client\Crm\Contacts in your case) based on API specification. The tool provide us a very limited control on how the generated client will look like.

Having this, need to investigate how chain calls could be implemented.

**Comment by ksvirkou-hubspot** [comment]
Hi @alexanderschnitzler 
starting from php 8.0 you can use [Nullsafe operator (?)](https://wiki.php.net/rfc/nullsafe_operator)
workable example 
```php
$apiResponse = $client->crm()->contacts()->basicApi()->getPage();

var_dump($apiResponse->getPaging()?->getNext()?->getAfter());
```
