### ISSUE TITLE
Search API delay after insert

### ISSUE THREAD

**Issue by powerbuoy** [HubSpot/hubspot-api-php#59]
After inserting a new contact using `\HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput` (I assume this happens with companies, deals etc too) and then immediately afterwards searching for said contact using `\HubSpot\Client\Crm\Contacts\Model\PublicObjectSearchRequest` it does not return any contact.

If you wait for an arbitrary amount of time and then search it does return a contact.

This is clearly a bug no? How can we get around it? We're importing thousands of contacts and sometimes the same contact shows up in the list twice, preventing our import script from running. This wouldn't be an issue if we were _only_ importing contacts but in the same script we create companies and deals too, and if the same contact shows up twice no deal is created.

Another, much better solution imo, would be to have a "create _or_ update" endpoint. That way we wouldn't even need to check if the contact exists first and could cut our code with like 75%.

**Comment by powerbuoy** [comment]
Also, the message we get back is: `{"status":"error","message":"Contact already exists. Existing ID: 6001","correlationId":"39b5e83f-bb85-4a01-8b8c-656b8ecc6f32","category":"CONFLICT"}`, if the "Existing ID" could be sent as a separate property we could actually _use_ that in the script. I don't feel comfortable stripping out the first 37 characters from the message as it'll break as soon as it changes.

**Comment by ksvirkou-hubspot** [comment]
HI @powerbuoy
it takes some time to update search indexes

**Comment by powerbuoy** [comment]
Ok... how about a createOrUpdate endpoint? At this point it alsmost feels easier to just run `update()` first and if that fails `create()`

**Comment by powerbuoy** [comment]
Or if at least the error message could include a property for the "Existing ID"?

**Comment by ksvirkou-hubspot** [comment]
This SDK is one to one with [New Hubspot API](https://developers.hubspot.com/docs/api/crm/contacts)
If HubSpot add `createOrUpdate` endpoint or `Existing ID` We will add it to the SDK
@powerbuoy
