### ISSUE TITLE
Possibility to get the original result (response)

### ISSUE THREAD

**Issue by alexanderschnitzler** [HubSpot/hubspot-api-php#6]
Hi folks,

do you plan to give the users an option to decide to return raw data instead of objects? As much as I like the client taking care of creating objects, in my use case I create custom object structures anyway and don't want to have the result as an object, convert it to raw data (`getProperties()`) and then unserialize into my object structure again.

It would be great to have an extra method (like all the async methods) that directly return the response and don't process it any further.

What do you think about that?

**Comment by yfaktor** [comment]
I think this is a dup of #7  - would you agree? Thanks

**Comment by alexanderschnitzler** [comment]
I don't fully understand the authors intent but it does not seem to be the same request. To me the issue mentioned in #7 sounds like a static json file which the objects are created from whereas I am talking about the individual json returned from your api which is not accessible when using your client because your client created objects and does not expose the response object which holds the json.

**Comment by yfaktor** [comment]
@alexanderschnitzler - sorry I misunderstood the request here. 
@atanasiuk-hubspot   - would calling  ObjectSerializer::sanitizeForSerialization() work for converting an Object back to Json?

**Comment by atanasiuk-hubspot** [comment]
> It would be great to have an extra method (like all the async methods) that directly return the response and don't process it any further.


Unfortunately, the client generated with [OpenAPI](https://github.com/OpenAPITools/openapi-generator) tool, doesn't currently expose the original Json response, so no way to get it directly.

As a workaround the response object can be casted to Json string manually:

```php
$apiResponse = $hubspot->crm()->contacts()->defaultApi()->getPage();
$jsonString = (string)$apiResponse;
```

And, yes, casting to "string" will use `ObjectSerializer::sanitizeForSerialization` method under the hood, as @yfaktor mentioned.

**Comment by yfaktor** [comment]
closing this because workaround was provided, but please reopen it if it doesn't work, thank you
