### ISSUE TITLE
No way to update a contact by email

### ISSUE THREAD

**Issue by jonmcclung** [HubSpot/hubspot-api-php#67]
`HubSpot\Client\Crm\Contacts\Api\BasicApi::update($contact_id, $simple_public_object_input)` corresponds to the `PATCH
/crm/v3/objects/contacts/{contactId}` endpoint of the API. However, the API allows you to update a contact by email by setting `idProperty` in the query params to `email`, such as this:

```
PATCH /crm/v3/objects/contacts/test@email.com?idProperty=email
```

While the php library offers no such convenience. We do not store the hubspot contact id in our database, but we need to keep hubspot updated of changes on our side using email as the identifier. What approach do you suggest to achieve this?

**Comment by powerbuoy** [comment]
We use `BasicApi::getById()` (which does allow you to set the id property to `email`) to first fetch the contact ID by e-mail, then we update it (or create it if non existent).

**Comment by ksvirkou-hubspot** [comment]
our SDK is one to one with API
This method doesn’t not exist in API
@jonmcclung

**Comment by Preen** [comment]
https://community.hubspot.com/t5/HubSpot-Ideas/Get-contact-by-email-api-v3/idi-p/463473
This clearly tells us that there is a getById(email)...

**Comment by ksvirkou-hubspot** [comment]
Hi @Preen 
Workable example
```php
$contact = $hubspot->crm()->contacts()->basicApi()->getByID('example@example.com', null, null, null, false, 'email');
var_dump($contact);
```

**Comment by ksvirkou-hubspot** [comment]
> https://community.hubspot.com/t5/HubSpot-Ideas/Get-contact-by-email-api-v3/idi-p/463473 This clearly tells us that there is a getById(email)...

Hi @Preen
Workable example
```Php
$contact = $hubspot->crm()->contacts()->basicApi()->getByID('example@example.com', null, null, null, false, 'email');
var_dump($contact);
```
