### ISSUE TITLE
GuzzleHTTP PSR7 not working

### ISSUE THREAD

**Issue by erbarratt** [HubSpot/hubspot-api-php#73]
in /codegen/Crm/Contacts/Api/BasicApi.php

Line 614 is $httpBody = \GuzzleHttp\Psr7\build_query($formParams);

Should be  $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);

Same for Line 643,

And presumably anywhere else trying to call now undefined functions....

**Comment by ksvirkou-hubspot** [comment]
Hi 
Could you check [this version](https://github.com/HubSpot/hubspot-api-php/releases/tag/5.0.0) please
