### ISSUE TITLE
Associations v4

### ISSUE THREAD

**Issue by alexgran** [HubSpot/hubspot-api-php#75]
Hi,
how about adding association v4 support? I know that this is beta, so likely on a branch. We are currently implementing this and would be cool not to reinvent the wheel.

regards
Alex

**Comment by dalefknight** [comment]
Myself and my team would also benefit from this.

**Comment by kbohan-code** [comment]
I agree that this would be greatly beneficial.

**Comment by chumanfu** [comment]
Can someone for the HubSpot team give an ETA on this please?
We are looking at using the V4 association endpoints and don't want to write our own code if you are going to be releasing some very soon.

**Comment by alexgran** [comment]
Here is our quite hacky solution:
Low level:
`<?php

namespace Bobbie\Hubspot\Model;

use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use HubSpot\Client\Crm\Tickets\ApiException;

/**
 * Adds manual v1&v4 api call support
 *
 */
class ManualApi
{
    const HOST = 'https://api.hubspot.com';
    /**
     * @var \GuzzleHttp\Client
     */
    protected $client;
    /**
     * @var string
     */
    protected $apiKey;

    public function init(\GuzzleHttp\Client $guzzleClient, \HubSpot\Config $config)
    {
        $this->client = $guzzleClient;
        $this->apiKey = $config->getApiKey();
    }

    /** Hubspot v4 Api is not yet part of their API client, so we do that here by ourselfs
     *
     */
    public function v4apiCallUnPaged(
        string $path,
        string $method = 'GET',
        $properties = null,
        $associations = null,
        $bodyParams = null
    ) {
        $after = '0';

        $results = [];
        do {
            $result = $this->apiCall($path, $method, $after, $properties, $associations, $bodyParams);
            if (isset($result['paging'])) {
                $after = $result['paging']['next']['after'];
            } else {
                $after = '0';
            }
            foreach ($result['results'] as $result) {
                $results[] = $result;
            }
        } while ($after !== '0');
        return $results;
    }

    /** Hubspot v4 Api is not yet part of their API client, so we do that here by ourselfs
     *
     */
    public function apiCall(
        string $path,
        string $method = 'GET',
        string $after = null,
        $properties = null,
        $associations = null,
        $bodyParams = null
    ) {
        $queryParams = [];
        $httpBody = '';

        $queryParams['limit'] = 500;
        if ($after != null && $after !== '0') {
            $queryParams['after'] = $after;
        }
        if ($properties !== null) {
            $queryParams['properties'] = $properties;
        }
        if ($associations !== null) {
            $queryParams['associations'] = $associations;
        }
        $headers['Content-Type'] = 'application/json';

        if ($bodyParams != null && ! is_string($bodyParams)) {
            $httpBody = \GuzzleHttp\json_encode($bodyParams);
        } else {
            $httpBody = $bodyParams;
        }

        // this endpoint requires API key authentication
        if ($this->apiKey !== null) {
            $queryParams['hapikey'] = $this->apiKey;
        }
        // this endpoint requires OAuth (access token)
        /*
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        */

        $headers['User-Agent'] = 'bobbie hubspot integration';

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        $request = new Request(
            $method,
            self::HOST . $path . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
        try {
            $response = $this->client->send($request, []);
        } catch (RequestException $e) {
            throw new ApiException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                $e->getResponse() ? (string) $e->getResponse()->getBody() : null
            );
        }

        $statusCode = $response->getStatusCode();

        if ($statusCode < 200 || $statusCode > 299) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $statusCode,
                    (string) $request->getUri()
                ),
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }
        return json_decode($response->getBody(), true);
    }

    public function needsInit()
    {
        return ($this->apiKey == null || $this->client == null);
    }

}
`

and usage like:
`   public function removeAssociations(
        string $fromObjectType,
        string $fromObjectId,
        string $toObjectType,
        string $toObjectId
    ) {
        return $this->manualApi()->apiCall(
            "/crm/v4/objects/$fromObjectType/$fromObjectId/associations/$toObjectType/$toObjectId",
            "DELETE"
        );
    }`

`    public function createAssociation($fromObjectType, $fromObjectId, $toObjectType, $toObjectId, $label = null)
    {
        $body = $this->getAssociationBody($fromObjectType, $toObjectType, $label);

        $this->manualApi()->apiCall(
            "/crm/v4/objects/$fromObjectType/$fromObjectId/associations/$toObjectType/$toObjectId",
            'PUT',
            0,
            null,
            null,
            $body
        );
    }

    public function getAssociations4(
        string $fromObjectType,
        string $fromObjectId,
        string $toObjectType
    ) {
        return $this->manualApi()->v4apiCallUnPaged(
            "/crm/v4/objects/$fromObjectType/$fromObjectId/associations/$toObjectType"
        );
    }

public function getAssociationBody($fromObjectType, $toObjectType, $label)
    {
        if ($label == null) {
            $label = "null";
        }
        $key = $fromObjectType . '_' . $toObjectType . '_' . $label;
        if (!isset($this->associationBodies[$key])) {
            $result =
                reset($this->manualApi()->apiCall(
                    "/crm/v4/associations/$fromObjectType/$toObjectType/labels"
                )['results']);

            //OBVIOUSLY, the create endpoint needs the arguments slightly different to the response above
            $this->associationBodies[$key] = json_encode([[
                'associationCategory' => $result['category'],
                'associationTypeId' => $result['typeId'],
            ]]);
        }
        return $this->associationBodies[$key];
    }


`

**Comment by ksvirkou-hubspot** [comment]
HI everyone 
Now associations v4 in Alpha 
When it's in beta, I'll publish it

**Comment by Muspi** [comment]
Hello, did you progress with V4 associations? best regards

**Comment by ksvirkou-hubspot** [comment]
Unfortunately no progress.

**Comment by Muspi** [comment]
There is no roadmap to support V4 of your API?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've just added Associations V4  in [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/9.3.0).
```javascript
$hubspot->crm()->associations()->v4();
```
