### ISSUE TITLE
How to set a PublicAssociationMulti 

### ISSUE THREAD

**Issue by pedramkat** [HubSpot/hubspot-api-php#77]
I need to associate many contacts to a deal but i could not find a way how to do it. Can anyone put an example here? it would be nice also if you could update the README.md with an example

**Comment by Theo4** [comment]
Hello,

Did you find something ?

Thanks,

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
Could you check [the docks](https://developers.hubspot.com/docs/api/crm/associations/v3)?
