### ISSUE TITLE
‘archived’ parameter in getPage method ignored

### ISSUE THREAD

**Issue by jordif** [HubSpot/hubspot-api-php#89]
Hi,

I’m trying to get a list of deleted companies using the getPage method:

https://github.com/HubSpot/hubspot-api-php/blob/0ab677f8ee5cfa663787d76df95c211abb6419cf/codegen/Crm/Companies/Api/BasicApi.php#L1038

However, the ‘archived’ parameter is ignored. Is this a bug or is this parameter not available yet in the API?

Thanks!

**Comment by ksvirkou-hubspot** [comment]
Hi @pqe-develop 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/5.1.1) please?

**Comment by jordif** [comment]
Hi @ksvirkou-hubspot !

Yes, it’s working now. Thanks so much!
