### ISSUE TITLE
How to set mandatory Deal Stage Properties

### ISSUE THREAD

**Issue by cincauhangus** [HubSpot/hubspot-api-php#9]
I'm trying to find the endpoint/payload to use to set the following settings available from the UI:

![image](https://user-images.githubusercontent.com/616127/84408002-2cee8380-ac3e-11ea-8193-4ebfe774e779.png)

Is it possible to set this via the API or only via UI?

**Comment by atanasiuk-hubspot** [comment]
Hey @cincauhangus!

Please check if [crm->pipelines](https://developers.hubspot.com/docs/api/crm/pipelines) is what you need.

**Comment by cincauhangus** [comment]
@atanasiuk-hubspot I've checked v1, v2 (crm-piplines) and v3 (crm->pipelines), all of them doesn't return or isn't able to set this information. If I've set certain properties to be mandatory on certain stages and made an update to the deal stages, the information is lost.

**Comment by cincauhangus** [comment]
Another thing to note, deal stage ids are required to be in lower case now, however older pipelines with upper case ids will need to be changed in order to update (https://github.com/HubSpot/hubspot-php/issues/295). 

I'm testing this under my HS test account and the deals under the upper case stage ids are no longer appearing in the board. They are still associated to the same pipeline.

![image](https://user-images.githubusercontent.com/616127/84583864-80c0be80-ae30-11ea-9ecb-615228b5e561.png)

In the image above `_01A` is the the old stage id, and the new stage is is `01a`.

**Comment by keshavnagpal** [comment]
is there any update for this?
need to fetch the required fields for each deal stage

**Comment by ksvirkou-hubspot** [comment]
Hi Everyone.
Hubspot API have no ability to manage deal stage properties, as far as I could find.
