### ISSUE TITLE
PHP 8.1 Deprecated

### ISSUE THREAD

**Issue by darkvovich** [HubSpot/hubspot-api-php#90]
`<b>Deprecated</b>:  Return type of HubSpot\\Client\\Crm\\Contacts\\Model\\Filter::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/vendor/hubspot/api-client/codegen/Crm/Contacts/Model/Filter.php</b> on line <b>360</b>

<b>Deprecated</b>:  Return type of HubSpot\\Client\\Crm\\Contacts\\Model\\Filter::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/vendor/hubspot/api-client/codegen/Crm/Contacts/Model/Filter.php</b> on line <b>372</b>`

**Comment by ksvirkou-hubspot** [comment]
@darkvovich  
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/6.0.0), please?
