### ISSUE TITLE
json  data sample object need

### ISSUE THREAD

**Issue by Sanjay-100** [HubSpot/hubspot-api-php#91]
HubSpot\Client\Crm\Contacts\ApiException: [400] Client error: `POST https://api.hubapi.com/crm/v3/objects/contacts?hapikey=1f430c92-a780-4a35-a7a0-f0546f8ebbcc` resulted in a `400 Bad Request` response:
{&quot;status&quot;:&quot;error&quot;,&quot;message&quot;:&quot;Invalid input JSON on line 1, column 15: Cannot construct instance of `java.util.LinkedHash (truncated...)

```

$contactInput = new \HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput();
$contactInput->setProperties($_POST);

$contact = $hubSpot->crm()->contacts()->basicApi()->create($contactInput);
```

**Comment by ksvirkou-hubspot** [comment]
Hi @Sanjay-100 
It is workable example 
```
$contactInput = new \HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput();
$contactInput->setProperties([
    'email' => 'example@example.com'
]);

$contact = $hubSpot->crm()->contacts()->basicApi()->create($contactInput);
```

**Comment by Sanjay-100** [comment]
> Hi @Sanjay-100 It is workable example
> 
> ```
> $contactInput = new \HubSpot\Client\Crm\Contacts\Model\SimplePublicObjectInput();
> $contactInput->setProperties([
>     'email' => 'example@example.com'
> ]);
> 
> $contact = $hubSpot->crm()->contacts()->basicApi()->create($contactInput);
> ```

can you pass the json ?

**Comment by ksvirkou-hubspot** [comment]
no it wouldn't work (I got 400 http error) 
but you can deserialize and pass
