### ISSUE TITLE
Archived basicApi not work

### ISSUE THREAD

**Issue by pqe-develop** [HubSpot/hubspot-api-php#98]
When I try to make a call with archived=true in PHP it return 404 error code:
e.g.
$resultDeal = $this->client->crm()->deals()->basicApi()->getById($this->hubspotId, $this->getProperties(), null, $associations, true, null);
version 5.1.0
I see when call Guzzle class (Query.php in namespace GuzzleHttp\Psr7; transform true in 1 and when it will call api return this error!!!
https://api.hubapi.com/crm/v3/objects/deals/8042865675?archived=1&hapikey=..... does not work!

**Comment by ksvirkou-hubspot** [comment]
Hi @pqe-develop 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-php/releases/tag/5.1.1) please?
